### ISSUE TITLE
apiSwap error: REQ_SWAP_RESPONSE_ERROR

### ISSUE THREAD

**Issue by MaeThird** [raydium-io/raydium-sdk-V2-demo#101]
I tried `apiSwap` in `src/api/swap.ts`. The `/main/auto-fee` and `/compute/swap-base-in` are correctly returned from server.But the `/transaction/swap-base-in` interface failed with `{"id":"a6381dfa-3bb8-4d3b-8ece-2b3ed4c831f8","success":false,"version":"V1","msg":"REQ_SWAP_RESPONSE_ERROR"}`. 
The `swapResponse` data is exactly the same from the `/compute/swap-base-in` .This is the JSON data in http body
` {"computeUnitPriceMicroLamports":"3000000","swapResponse":{"inputAmount":"100000000","inputMint":"So11111111111111111111111111111111111111112","otherAmountThreshold":"38293380","outputAmount":"38331712","outputMint":"GJAFwWjJ3vnTsrQVabjBVK2TYB1YtRCQXRDfDgUnpump","priceImpactPct":0.0,"routePlan":[{"feeAmount":"250000","feeMint":"So11111111111111111111111111111111111111112","feeRate":25.0,"inputMint":"So11111111111111111111111111111111111111112","outputMint":"GJAFwWjJ3vnTsrQVabjBVK2TYB1YtRCQXRDfDgUnpump","poolId":"B4PHSkL6CeZbxVqm1aUPQuVpc5ERFcaZj7u9dhtphmVX"}],"slippageBps":10.0,"swapType":"BaseIn"},"txVersion":"V0","unwrapSol":false,"wallet":"CNUi1NYUgxJDcnq5xke7DqpH7ZTfPzQ8n3BBh8K3sEGZ","wrapSol":true}`

There is no document about this error. Any help?

**Comment by MaeThird** [comment]
Oh, it was my mistake, sorry.

**Comment by pmmlpmmlpmmlpmml** [comment]
> Oh, it was my mistake, sorry.

Bro help! I'm already exhausted! How did you solve the problem? please tell me

**Comment by akSolkhatri** [comment]
Any solution ????

**Comment by akSolkhatri** [comment]
> Oh, it was my mistake, sorry.

@MaeThird  bro please help here !!!!

**Comment by MaeThird** [comment]
It's been a long time, and I just saw the message. Sorry about that. This is the json data of ```/transaction/swap-base-in```

```
        if !is_input_sol {
            //sell out
            if let Some(input) = input_ata {
                input_account = Some(input);
            }
        }
        if !is_output_sol {
            //buy in
            if let Some(output) = output_ata {
                output_account = Some(output);
            }
        }

        let path = format!("{}{}", RAYDIUM_HOST_SWAP, "/transaction/swap-base-in");
        let url_swap_post = Url::parse(path.as_str()).unwrap();
        let swap_data = SwapData {
            compute_unit_price_micro_lamports: (fee as u64).to_string(),
            tx_version: tx_version.to_string(),
            wallet: wallet_address.to_string(),
            wrap_sol: is_input_sol,
            unwrap_sol: is_output_sol,
            input_account: input_account,
            output_account: output_account,
            swap_response: swap,
        };
        debug!("{:?}", swap_data);
```
the ```swap``` data is from ```/compute/swap-base-in```

These two api are just for play toy. In practice it failed more 2/3 because of 'blockhash was not found' which means timeout when processed through this two requests. The slot time is about 400ms,so heavy failure is expected. I suggest use their sdk or directly call their onchain contract which is my way. @akSolkhatri
