### ISSUE TITLE
apiSwap Demo returns  REQ_SWAP_RESPONSE_ERROR

### ISSUE THREAD

**Issue by klauskobald** [raydium-io/raydium-sdk-V2-demo#103]
I tried different token pairs. A more descriptive error would be nice!

**Comment by cruzshia** [comment]
please follow demo code https://github.com/raydium-io/raydium-sdk-V2-demo/blob/master/src/api/swap.ts
to do api swap and 'do not' hard code params like `swapResponses`, you also can compare api request in raydium.io to check whether there's any wrong params send to api.
if you send api request like raydium.io does but still receive errors, please open a support tick in discord, thanks

**Comment by magentoman2009** [comment]
Just posting this to help others out in case @cruzshia answer doesn't help. No need to reopen this ticket...

In my case, for whatever reason, when you fetch the quote the const variable name must be swapResponse! I tried using a different name and I received that generic error. Took me hours to figure that out! Hope this helps someone else!

```
    let { data: swapResponse } = await axios.get<SwapCompute>(
      `${
        API_URLS.SWAP_HOST
      }/compute/swap-base-in?inputMint=${inputMint}&outputMint=${outputMint}&amount=${amount}&slippageBps=${
        slippage * 100
      }&txVersion=${txVersion}`
```
