### ISSUE TITLE
Cannot get fetchPoolById for specific pool ids

### ISSUE THREAD

**Issue by tushar-sahoo** [raydium-io/raydium-sdk-V2-demo#108]
`6rXSohG2esLJMzKZzpFr1BXUeXg8Cr5Gv3TwbuXbrwQq`

This is a token pool id

```
const data = await raydium.api.fetchPoolById({ ids: poolId });
```

I want to fetch the pool data by using the raydium api but it returns null for some reason

https://dexscreener.com/solana/6rxsohg2esljmzkzzpfr1bxuexg8cr5gv3twbuxbrwqq

But the CPMM pool exists and the api is working for other pools.

**Comment by cruzshia** [comment]
we are checking this, if you need fetch pool info to call other cpmm methods, please call rpc to get info at this moment https://github.com/raydium-io/raydium-sdk-V2-demo/blob/master/src/cpmm/deposit.ts#L22

**Comment by cruzshia** [comment]
fixed. api can return pool info now
