### ISSUE TITLE
How can we add liquidity while creating CLMM pool?

### ISSUE THREAD

**Issue by lazydevpro** [raydium-io/raydium-sdk-V2-demo#113]
I am trying to create a CLMM pool and would like to know if I can add liquidity and pool creation directly in a single transaction like in the CPMM example.

I tried looking for any resource mentioning it but found no help.

**Comment by cruzshia** [comment]
cpmm's contract supports adding initial liquidity when creating pool but clmm doesn't, so it need to separate 2 instructions, if you bind create clmm pool and open position in 1 tx, it will exceed tx size limit, so it's not possible.
