### ISSUE TITLE
Not work withdrawLiquidity.ts

### ISSUE THREAD

**Issue by phakel21** [raydium-io/raydium-sdk-V2-demo#114]
When i run withdrawLiquidity.ts i get
#3 - Unknown: Unknown
(Program Error: "custom program error: InvalidInput")

UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Object]".
    at throwUnhandledRejectionsMode (node:internal/process/promises:392:7)
    at processPromiseRejections (node:internal/process/promises:475:17)
    at processTicksAndRejections (node:internal/process/task_queues:106:32) {
  code: 'ERR_UNHANDLED_REJECTION'
}

I have LP tokens on wallet which use in config.ts
Why poolInfo.lpAmount = 0?
Total supply LP tokens: 199

When use slippage 100% and const withdrawLpAmount = new BN(100) (i have only 100 tokens) transaction confirmed but I still have 100 LP tokens and no base or quote tokens?

**Comment by Saoiray405** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by berryMo27** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Raydium Support](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by cruzshia** [comment]
update a commit here: https://github.com/raydium-io/raydium-sdk-V2-demo/commit/7b71c8fd5e037a8ea7f6d8cba1ee471bfb10cf70
you can try again, if not, please provide pool id.
note: please ensure your withdraw liquidity amount is correct

**Comment by phakel21** [comment]
Pool id: FcZNWMNEyUrPY7GMqC92xiWV5otqjCHisUznFJApj8FH
Account for withdraw liquidity: 9XLoy41B1NehiWDxzbYzRDjVkJxhPrmY3XWRsk66f2kK

import { ApiV3PoolInfoStandardItem, AmmV4Keys, AmmV5Keys } from '@raydium-io/raydium-sdk-v2'
import { initSdk, txVersion } from '../config'
import BN from 'bn.js'
import Decimal from 'decimal.js'
import { isValidAmm } from './utils'

export const withdrawLiquidity = async () => {
  const raydium = await initSdk()

  const poolId = 'FcZNWMNEyUrPY7GMqC92xiWV5otqjCHisUznFJApj8FH'
  let poolKeys: AmmV4Keys | AmmV5Keys | undefined
  let poolInfo: ApiV3PoolInfoStandardItem
  const withdrawLpAmount = new BN(10)

  if (raydium.cluster === 'mainnet') {

    const data = await raydium.api.fetchPoolById({ ids: poolId })
    poolInfo = data[0] as ApiV3PoolInfoStandardItem
  } else {
    
    const data = await raydium.liquidity.getPoolInfoFromRpc({ poolId })
    poolInfo = data.poolInfo
    poolKeys = data.poolKeys
  }

  console.log(poolInfo.lpAmount)

  if (!isValidAmm(poolInfo.programId)) throw new Error('target pool is not AMM pool')
  const [baseRatio, quoteRatio] = [
    new Decimal(poolInfo.mintAmountA).div(poolInfo.lpAmount || 1),
    new Decimal(poolInfo.mintAmountB).div(poolInfo.lpAmount || 1),
  ]

  const withdrawAmountDe = new Decimal(withdrawLpAmount.toString()).div(10 ** poolInfo.lpMint.decimals)
  const [withdrawAmountA, withdrawAmountB] = [
    withdrawAmountDe.mul(baseRatio).mul(10 ** (poolInfo?.mintA.decimals || 0)),
    withdrawAmountDe.mul(quoteRatio).mul(10 ** (poolInfo?.mintB.decimals || 0)),
  ]

  const lpSlippage = 0.003

  const { execute } = await raydium.liquidity.removeLiquidity({
    poolInfo,
    poolKeys,
    lpAmount: withdrawLpAmount,
    baseAmountMin: new BN(withdrawAmountA.mul(1 - lpSlippage).toFixed(0)),
    quoteAmountMin: new BN(withdrawAmountB.mul(1 - lpSlippage).toFixed(0)),
    txVersion,

  })


  const { txId } = await execute({ sendAndConfirm: true })
  console.log('liquidity withdraw:', { txId: `https://explorer.solana.com/tx/${txId}` })
  process.exit() 
}

withdrawLiquidity()

poolInfo.lpAmount still 0

**Comment by phakel21** [comment]
I even agree to 100% slippage

**Comment by cruzshia** [comment]
after checking, you are using devnet pool info.
just updated lp Amount from rpc pool info in sdk (https://github.com/raydium-io/raydium-sdk-V2-demo/commit/cbedcb17aa3803c5650625ccbdef6c68480549e2), and test withdraw liquidity from provided account with 10% slippage,
simulation went though.
you can test it.
