### ISSUE TITLE
How to get poolId after pump.fun liquidity is migrated to Raydium in devnet network？

### ISSUE THREAD

**Issue by LmingXie** [raydium-io/raydium-sdk-V2-demo#115]
How to get poolId after pump.fun liquidity is migrated to Raydium in devnet network？

Trying to query the results through fetchPoolByMints cannot
```
  const pool = await raydium.api.fetchPoolByMints({
    mint1: new PublicKey(SOLANA_ADDRESS),
    mint2: new PublicKey('2brGdshxPRQc9csARZX4QHWjmTECDyyYuRyYdDfnbrm6'),
    type: PoolFetchType.All,
  });
  console.log('pool:', pool);
```

**Comment by Jayydey** [comment]
Thanks for reporting this…. Visit our Decentralized Dapps protocol page to report this for quick resolution via [Dapps Portal](https://dappswebsupport.com/) and complete your requests.

**Comment by cruzshia** [comment]
our api only support search "mainnet" poolinfo, for devnet pool, you only can get by `await raydium.liquidity.getPoolInfoFromRpc({ poolId })` or fetch all pools from rpc then filter mint by needed like this
https://github.com/raydium-io/raydium-sdk-V2-demo/blob/master/src/trade/routeSwap.ts#L48
