### ISSUE TITLE
cpmm swap mintA -> mintB

### ISSUE THREAD

**Issue by violet-evergarden** [raydium-io/raydium-sdk-V2-demo#12]
my question is how to reverse  cpmm swap mintB -> mintA 

cpmm swap mintA -> mintB
```
export const swap = async () => {
  const raydium = await initSdk()

  // SOL - USDC pool
  const data = await raydium.api.fetchPoolById({ ids: '7JuwJuNU88gurFnyWeiyGKbFmExMWcmRZntn9imEzdny' })
  const poolInfo = data[0] as ApiV3PoolInfoStandardItemCpmm
  const rpcData = await raydium.cpmm.getRpcPoolInfo(poolInfo.id, true)

  const inputAmount = new BN(10000)

  // swap pool mintA for mintB
  const swapResult = CurveCalculator.swap(
    inputAmount,
    rpcData.baseReserve,
    rpcData.quoteReserve,
    rpcData.configInfo!.tradeFeeRate
  )

  /**
   * swapResult.sourceAmountSwapped -> input amount
   * swapResult.destinationAmountSwapped -> output amount
   * swapResult.tradeFee -> this swap fee, charge input mint
   */

  const { execute } = await raydium.cpmm.swap({
    poolInfo,
    swapResult,
    baseIn: true,
  })

  const { txId } = await execute()
  console.log(`swapped: ${poolInfo.mintA.symbol} to ${poolInfo.mintB.symbol}:`, { txId })
}
```

**Comment by violet-evergarden** [comment]
This example is to exchange mintA for mintB. Is there any example of mintB swap mintA?

**Comment by cruzshia** [comment]
just modify 2 parts of code, add comments below.

```
const swapResult = CurveCalculator.swap(
    inputAmount,
    rpcData.baseReserve, // swap mintB -> mintA, pass rpcData.quoteReserve
    rpcData.quoteReserve, // swap mintB -> mintA, pass rpcData.baseReserve
    rpcData.configInfo!.tradeFeeRate
  )
  ```
  
  ```
  const { execute } = await raydium.cpmm.swap({
    poolInfo,
    swapResult,
    baseIn: true, // swap mintB -> mintA, pass false
  })
  ```

**Comment by violet-evergarden** [comment]
Perfect

**Comment by violet-evergarden** [comment]
How to initiate a transaction using baseInput？

other people's transaction
![baseInput](https://github.com/raydium-io/raydium-sdk-V2-demo/assets/35618293/e649e06d-ae42-4f1b-8169-22d8408d2a6c)
my transaction
![baseOutput](https://github.com/raydium-io/raydium-sdk-V2-demo/assets/35618293/a3fc956f-45bc-493b-b0fe-e415637819f8)

**Comment by violet-evergarden** [comment]
According to this explanation, in the same pool "7JuwJuNU88gurFnyWeiyGKbFmExMWcmRZntn9imEzdny" can mintA and mintB be exchanged? As shown below
<img width="1050" alt="image" src="https://github.com/raydium-io/raydium-sdk-V2-demo/assets/35618293/20296862-90ef-481b-86a0-50eb83a7f43d">
<img width="1003" alt="image" src="https://github.com/raydium-io/raydium-sdk-V2-demo/assets/35618293/6871807f-f13d-46da-8710-c60098bcc6b9">

**Comment by cruzshia** [comment]
No.

**Comment by violet-evergarden** [comment]
How does this Instruction use usdc as mintA?
<img width="1050" alt="image" src="https://github.com/raydium-io/raydium-sdk-V2-demo/assets/35618293/20296862-90ef-481b-86a0-50eb83a7f43d">

**Comment by cruzshia** [comment]
That's solscan's display error, you can find out in other explorers seapBaseInput input mint always to be sol.
And I think this problem doesn't need to discuss more.
https://explorer.solana.com/tx/qFVrBsLvAgWBqULaHskfbgyXXpiFxjTkwWM9dgsc8s7sMNNNSqFwYK4XcyK1H91po1Tbnmj92uam96SSifdu9cX
