### ISSUE TITLE
how can I get the API_HOST for devnet?

### ISSUE THREAD

**Issue by cmzc** [raydium-io/raydium-sdk-V2-demo#13]
hi~  I was testing the fetching pool information about devnet, but was denied. 
   
```log
2024/05/29 03:33:50 UTC Raydium_Api sdk logger error GET https://api-v3.raydium.io/pools/info/ids?ids=7JuwJuNU88gurFnyWeiyGKbFmExMWcmRZntn9imEzdny 403
```

As a visitor, how can I get the api_host?  
thxs

**Comment by cruzshia** [comment]
api doesn't support get denvet pools at this moment and doesn't have schedule, so just can test pool related on mainnet
