### ISSUE TITLE
amm swap mintB -> mintA

### ISSUE THREAD

**Issue by miaoluyao** [raydium-io/raydium-sdk-V2-demo#14]

**Comment by miaoluyao** [comment]
my question is how to reverse amm swap mintB -> mintA

**Comment by cruzshia** [comment]
check out lastest code with comment swap mintB -> mintA (total 3 lines). also remember run yarn to update sdk
https://github.com/raydium-io/raydium-sdk-V2-demo/blob/master/src/amm/swap.ts#L30

**Comment by miaoluyao** [comment]
`\solana\raydium-sdk-V2-demo\node_modules\@raydium-io\raydium-sdk-v2\src\raydium\liquidity\liquidity.ts:690  
    if (mintIn !== poolInfo.mintA.address && mintIn !== poolInfo.mintA.address) throw new Error("toke not match");
                                                                                      ^
Error: toke not match
    at Qr.computeAmountOut (D:\bob\solana\raydium-sdk-V2-demo\node_modules\@raydium-io\raydium-sdk-v2\src\raydium\liquidity\liquidity.ts:690:87)
    at D:\bob\solana\raydium-sdk-V2-demo\src\amm\swap.ts:23:33
    at Generator.next (<anonymous>)
    at fulfilled (D:\bob\solana\raydium-sdk-V2-demo\src\amm\swap.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by cruzshia** [comment]
run yarn install to update sdk before run demo.

**Comment by miaoluyao** [comment]
Perfect
