### ISSUE TITLE
How can I get poolId after createAmmPool trx success?

### ISSUE THREAD

**Issue by dexweb3** [raydium-io/raydium-sdk-V2-demo#15]
How can I get poolId after createAmmPool trx success?

https://github.com/raydium-io/raydium-sdk-V2-demo/blob/50b69737f341e542f7eed2b77bd03da9d638404f/src/amm/createAmmPool.ts#L56

I didn't find it at extInfo too (like it was able for marketId)

**Comment by cruzshia** [comment]
all publicKey contain in extInfo.address, for pool id: **extInfo.address.ammId** 
https://github.com/raydium-io/raydium-sdk-V2-demo/blob/50b69737f341e542f7eed2b77bd03da9d638404f/src/amm/createAmmPool.ts#L26

**Comment by dexweb3** [comment]
Ah, sure, ammId. Thanks again @cruzshia for quick help
