### ISSUE TITLE
Raydium fetchPoolById return null for exist poolId (devnet)

### ISSUE THREAD

**Issue by dexweb3** [raydium-io/raydium-sdk-V2-demo#16]
https://github.com/raydium-io/raydium-sdk-V2-demo/blob/15b3620f8efdb6567b258c387c42008dd7e1ce3a/src/amm/swap.ts#L11

Pool creation tx: https://explorer.solana.com/tx/4URxQpz9ByTutypYAgTKftJsaT2N2iUmcypadFVhA3Dhuu1ogHCnzbaQJPk9ycDAPAB4AWFCXHhwVEaQ3HXZsh4c?cluster=devnet

Pool: https://explorer.solana.com/address/7HtQNPDxxsKUsDUq6GiryFcsUyufcgnfHqWPWnB3XFG8?cluster=devnet

PoolId: 7HtQNPDxxsKUsDUq6GiryFcsUyufcgnfHqWPWnB3XFG8

**raydium.api.fetchPoolById return NULL at response** 
![image](https://github.com/raydium-io/raydium-sdk-V2-demo/assets/169032650/08f9174d-f509-4157-844d-7eb514feb5ef)

Is it require any adoptation for devnet?

**Comment by cruzshia** [comment]
our api doesn't support devent pool data at this moment and still don't have schedule to support it.
if you want to try swap, recommend to use small amount on mainnet to test.
