### ISSUE TITLE
CLMM swap doesn't work

### ISSUE THREAD

**Issue by MacroChip** [raydium-io/raydium-sdk-V2-demo#17]
raydium-sdk-V2-demo/node_modules/@raydium-io/raydium-sdk-v2/src/raydium/clmm/utils/tick.ts:229
      ...[...exTickArrayBitmap.negativeTickArrayBitmap].reverse(),
                                          ^
TypeError: Cannot read properties of undefined (reading 'negativeTickArrayBitmap')

All I did was npm install, put in my secret key, put in my helius rpc url, uncomment the swap function in the clmm swap demo, and npm run dev -- src/clmm/swap.ts

exBitmapInfo is undefined in the response from fetchComputeClmmInfo

**Comment by cruzshia** [comment]
pull latest code and run yarn install, it works now.

**Comment by MacroChip** [comment]
thanks
