### ISSUE TITLE
getRpcPoolInfo Error: pool vaultA info not found

### ISSUE THREAD

**Issue by AriesOpenAi** [raydium-io/raydium-sdk-V2-demo#18]
hello，
 // SOL - USDC pool
  const data = await raydium.api.fetchPoolById({ ids: 'AVs9TA4nWDzfPJE9gGVNJMVhcQy3V9PGazuz33BfG2RA' })
  const poolInfo = data[0] as ApiV3PoolInfoStandardItemCpmm
  const rpcData = await raydium.cpmm.getRpcPoolInfo(poolInfo.id, true)
Error: pool vaultA info not found
What is the reason?

**Comment by cruzshia** [comment]
AVs9TA4nWDzfPJE9gGVNJMVhcQy3V9PGazuz33BfG2RA is standard amm pool, please run scripts in src/amm/xxx.ts
