### ISSUE TITLE
The amm/swap handling fee is too high. When I use https://raydium.io/ it is very low. Is there any way to optimize it?

### ISSUE THREAD

**Issue by miaoluyao** [raydium-io/raydium-sdk-V2-demo#19]
If the priority fee I use is too low, has expired: block height exceeded will appear.（If the computeBudgetConfig parameter is not passed, "has expired: block height exceeded." will also appear.）
How should I set a reasonable prioritization fee?

Below is a comparison of the two transactions

[raydium.io  solscan  0.000022186 SOL](https://solscan.io/tx/3czZkty9p81Ev9Z81q5jtU4VdgJR7BJtaQa4jEeDNNitq79NQwuijEMiYrMufpWTYJU9t9NCbs7FqDpWTecQDSPY)

[raydium-sdk-V2-demo  0.060005 SOL](https://solscan.io/tx/zomJeHbQHCW4SXUndGJWma17VteNT74E9oj5ENnwqHsnfpJmusYvojzbxo3NDgjDf2FKYw3h6PJD6tvU6XhczoR)

**Comment by cruzshia** [comment]
you can check realtime average fees in [here](https://www.quicknode.com/gas-tracker/solana)
if you want to go through smoothly, better set equal or higher than 'high' level.

<img width="1299" alt="image" src="https://github.com/raydium-io/raydium-sdk-V2-demo/assets/6680106/c3dea9c9-168c-4ed8-a3af-2df45e560a5b">

**Comment by cruzshia** [comment]
yes, if it's also too slow, you also can watch avg fees here. 
note: sol * 10**9 = microlamports
https://solanacompass.com/
<img width="1204" alt="image" src="https://github.com/raydium-io/raydium-sdk-V2-demo/assets/6680106/3aae0df9-469f-44c8-a4d4-52c5f99286b6">

**Comment by miaoluyao** [comment]
`const getFeesInfo = async () => {
  try {
    const response = await axios.get('https://solanacompass.com/api/fees?cacheFreshTime=' + (5 * 60 * 1000));
    const json = response.data;
    const { avg } = json?.[15] ?? {};

    if (!avg) {
      return undefined;
    }
    return Math.ceil(avg);
  } catch (error) {
    console.error('Error fetching fees info:', error);
    return undefined;
  }
};
const microLamports = await getFeesInfo();`

Thanks
