### ISSUE TITLE
Connect wallet first while calling execute

### ISSUE THREAD

**Issue by mehranml** [raydium-io/raydium-sdk-V2-demo#2]
i getting Uncaught (in promise) Error: please connect wallet first when i try call execute on raydium.clmm.openPositionFromBase as example

**Comment by cruzshia** [comment]
replace `<YOUR_WALLET_SECRET_KEY>` in config.ts.
```
export const owner: Keypair = Keypair.fromSecretKey(bs58.decode('<YOUR_WALLET_SECRET_KEY>'))
```
