### ISSUE TITLE
How to load Raydium with fetched tokenAccount by default?

### ISSUE THREAD

**Issue by dexweb3** [raydium-io/raydium-sdk-V2-demo#20]
https://github.com/raydium-io/raydium-sdk-V2-demo/blob/6c0404904a561558ff15c40907c0838552ae1be7/src/config.ts.template#L13

When load Raydium it doesn't provide data about tokenAccount by default. It updates after manipulation only (buy or sell something, for example). 
Is it possible to get it before make transaction?

**Comment by cruzshia** [comment]
await radium.account.fetchWalletTokenAccounts()

then you can access account related data in raydium.account object

**Comment by dexweb3** [comment]
Thanks @cruzshia 👍
