### ISSUE TITLE
TransactionExpiredBlockheightExceededError: Signature has expired: block height exceeded

### ISSUE THREAD

**Issue by wxpkerpk** [raydium-io/raydium-sdk-V2-demo#26]
“When I use this demo to create a CPMM pool, I encounter an error 100% of the time.”
simulate tx string: [
  'AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAQAJE4Ae3VwHDaFxdHtMuPV5bm1cNtU+JaquCBzlC03ABCfd2Y00ksLrgYo8jp6JiUQmV1GitIfh1TCds6pgP9qe/mmQBdTVYijPJWXWgdZhgBEgO7WX3Pp8W+cryDEaqPbqiDPoa7ZPcHihKCoGq+jFTBV+VQk1CB1xvy5WAnMQ4I4/Wp1Gu5JN3402qD0y9V6HrRHEYC9vvBVe/sSZNSi1/xJNbScPIJnF5dVjaAdJFNNXBkmeNTPiGYaoQZ25erpVC7RiEFV4BoDMbu4dVUIEA/+yFQFmFsyw8qNzvoThDSnTwFg/dP+uV08G+KnuvI/5BrqOLglfF0tseZnyuxdJ8pC30CJSVKwH47K9P4bB8PEQP8BwjMFa7xQHOqZFP1XqaR4avkWxOZSQ99YtnQtc1DMtXQG7y/IUogd49d3pA/8bqSpai08pWVKEJVCqk/1blbWs5qjrkgyTlC5DaQwg7HOzIT+6i/nIf6keR4GWKMOD4AvqfpjHoD4DuhBpz8P28+sA2fWykrQhSsfQN7TW8GRQuWRgDfNzBSu16E8vjppnIEe9AbSMZZ0DKTyQ7i/2B8MCu/qTgltbZw1mVD9ZXIg/DsI46YZMkhfo51h3AmKM9PMABQ738G1v12g9MA83wwbd9uHXZaGT2cvhRs7reawctIXtX1s3kTqM9YV+/wCpjJclj04kifG7PRApFI4NgwtaE5na/xCEBI572Nvp+FkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAan1RcZLFxRIYzJTD1K8X9Y2u4Im6H9ROPb2YoAAAAA4d+1e0ftCAYyh5UFN0UjLuhp5m5OLMOmFd5ZLTfD+DQBChQACwwBDQ4CAwQFBgcICQ8PDxAREiCvr20fDZib7WQAAAAAAAAAZAAAAAAAAAAAAAAAAAAAAAA='
]
/var/raydiumsdkdemo/raydiumsdkv2/node_modules/@solana/web3.js/lib/index.cjs.js:6565
        throw new TransactionExpiredBlockheightExceededError(signature);
              ^

TransactionExpiredBlockheightExceededError: Signature 2mWYdZU3cds6rPCGibqHceXfHjVaFTQibJZpiEN3MEvPYX6apneV1rCwqu7goHMrmwcmoHmGsfE8CiwCBr4mN9N1 has expired: block height exceeded.
    at Connection.confirmTransactionUsingBlockHeightExceedanceStrategy (/var/raydiumsdkdemo/raydiumsdkv2/node_modules/@solana/web3.js/lib/index.cjs.js:6565:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Connection.confirmTransaction (/var/raydiumsdkdemo/raydiumsdkv2/node_modules/@solana/web3.js/lib/index.cjs.js:6393:14)
    at async execute (/var/raydiumsdkdemo/raydiumsdkv2/node_modules/@raydium-io/raydium-sdk-v2/lib/index.js:1:74821)
    at async exports.createPool (/var/raydiumsdkdemo/raydiumsdkv2/js/cpmm/createCpmmPool.js:50:22) {
  signature: '2mWYdZU3cds6rPCGibqHceXfHjVaFTQibJZpiEN3MEvPYX6apneV1rCwqu7goHMrmwcmoHmGsfE8CiwCBr4mN9N1'
}

**Comment by cruzshia** [comment]
Set higher priority fee(computeBudgetConfig)
