### ISSUE TITLE
problem to find `poolId`

### ISSUE THREAD

**Issue by kasrakhamesi** [raydium-io/raydium-sdk-V2-demo#3]
where can find   const poolId = '6UmmUiYoBjSrhakAobJw8BvkmJtDVxaeBtbt7rxWo1mg' ?

pool id for pairs ?

**Comment by cruzshia** [comment]
you can search target pool id via [Raydium UI](https://raydium.io/liquidity-pools/?tab=all)
<img width="966" alt="image" src="https://github.com/raydium-io/raydium-sdk-V2-demo/assets/6680106/b4494b02-ef7e-4b5b-8264-dda267a91a32">

**Comment by kasrakhamesi** [comment]
I need find pool with search in API for back-end,not need find it with raydium ui.
