### ISSUE TITLE
Pool Information Null When Fetching by ID

### ISSUE THREAD

**Issue by bl4ckh401** [raydium-io/raydium-sdk-V2-demo#33]
I'm experiencing an issue where fetching a pool by its ID using the Raydium SDK returns null. Despite passing a valid pool ID, the fetched pool data is null, which prevents further actions such as executing a swap.

Below is the detailed error and the relevant parts of my code:

**Error and Results:**
`Initializing Raydium SDK...
Target Pool ID: 21BuLR6csZKGgQfFNWgf9mNWyjHG5cNV8JwAxXdTA1m4
Fetching pool by ID...
Fetched Pool Data: [ null ]
Error in swapOnlyAmmV2: Error: Pool information is null or undefined
    at swapOnlyAmmV2 (C:\Users\Admin\Desktop\SMEV\src\controller\tradeToken.ts:42:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at fetchRaydiumMints (C:\Users\Admin\Desktop\SMEV\src\controller\lpTracker.ts:139:26)
    at C:\Users\Admin\Desktop\SMEV\src\main.ts:32:40`
    
 **Code:**  

`try {
    console.log("Initializing Raydium SDK...");
    const amountIn = 100;
    const raydium = await initSdk();
    if (!raydium) throw new Error("Failed to initialize Raydium SDK");
    
    const poolId = input?.targetPool.toString();
    console.log("Target Pool ID:", poolId);

    console.log("Fetching pool by ID...");
    const data = await raydium.api.fetchPoolById({ ids: poolId });
    console.log("Fetched Pool Data:", data);
    
    const poolInfo = data ? data[0] as ApiV3PoolInfoStandardItem : null;
    if (!poolInfo) throw new Error("Pool information is null or undefined");
    console.log("Fetched Pool Info:", poolInfo);
`
**Expected Behavior**
The pool information should not be null when fetching by a valid pool ID, and the swap should be executed successfully.

**Actual Behavior**
The pool information is null despite passing a valid pool ID, causing the process to fail.

**Additional Information**
- The Raydium SDK initialization appears to be successful.
- The getAmmPoolKeys function also returns valid keys.

Could you please help me understand why the pool information is null and how to resolve this issue?

Thank you for your assistance!

**Comment by cruzshia** [comment]
api looks ok, could you confirm your api request url?
`https://api-v3.raydium.io/pools/info/ids?ids=21BuLR6csZKGgQfFNWgf9mNWyjHG5cNV8JwAxXdTA1m4`

After testing, code below works well in my end
```
const data = await raydium.api.fetchPoolById({ ids: '21BuLR6csZKGgQfFNWgf9mNWyjHG5cNV8JwAxXdTA1m4' })
const poolInfo = data[0] as ApiV3PoolInfoStandardItem
```
