### ISSUE TITLE
Program returned error: custom program error: 0x1d

### ISSUE THREAD

**Issue by miaoluyao** [raydium-io/raydium-sdk-V2-demo#34]
This tx[solscan](https://solscan.io/tx/2VAy7vfas2RCwL8rQX9auZoc42e98hnZQqNCq2wBtxZiNvSChZVTSgZV34BaWniuHJDKgyMoFYzGCSBf1A9qzHxg)

`amm/swap
const amountIn = 0.01
const poolId = 'EieyicTUK1iacEAd1eGeDasq9CijwBeqmtn3Rs8RpeA1'
const out = raydium.liquidity.computeAmountOut({
poolInfo: {
  ...poolInfo,
  baseReserve: pool.baseReserve,
  quoteReserve: pool.quoteReserve,
},
amountIn: new BN(amountIn),
mintIn: poolInfo.mintB.address, // swap mintB -> mintA, use: poolInfo.mintB.address
mintOut: poolInfo.mintA.address, // swap mintB -> mintA, use: poolInfo.mintA.address
slippage: 0.9, // range: 1 ~ 0.0001, means 100% ~ 0.01%
})

const { execute } = await raydium.liquidity.swap({
poolInfo,
amountIn: new BN(amountIn),
amountOut: out.minAmountOut, // out.amountOut means amount 'without' slippage
fixedSide: 'in',
inputMint: poolInfo.mintB.address, // swap mintB -> mintA, use: poolInfo.mintB.address
associatedOnly: false,
txVersion,
// optional: set up priority fee here
computeBudgetConfig: {
  units: 600000,
  microLamports: 289137,
},
})`

**Comment by miaoluyao** [comment]
[raydium.io success](https://solscan.io/tx/JixqiaDFo2NGaLa2Zj9QpBjpdf1HLoX4R1SLtGiHNGttLDS3RMh6HyiAQka1JBTuFjCXropCtQdCX67QjBschoh)

**Comment by SwapnilSoni1999** [comment]
got any solution for this?
