### ISSUE TITLE
Failed to create new Ammpools, error code: custom program error: 0x10001a9

### ISSUE THREAD

**Issue by kundingwhale** [raydium-io/raydium-sdk-V2-demo#35]
Failed to create ammpools in devnet environment, error code:0x10001a9
simulate tx string: [
'AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAQALFl78WF9/GoseNdcxvj6DlDavbNt7iALEGC82s6pxCcRNYpoeQ6tKKRRuhPi5JbnzkaZwoCg7BW3TKad/vtcr4WzInT8/uEFfhVoi58Sr13dKWOuMU2XxVQEq+dcJLQ6mUa8ZdIpnduemdyfrGT/9pfXd9w9vs/6dZZIvcxAltBO8AAd/1PhLbSiSEwqfADut1ws55P1Rvgc77Sxp9D3roF2cVZO9ZY6q2L4llmyD9Jb5fPihdkx6FzSDfe8xPVlK8CzTopNHl7HdH/xuaxbmtz8QP+4hIx5MO/s7C9KAd/eX9kOFoZBWviuixb+yL+4MGs3S7pbWL9xc9AogoLuUk6clfmGPXBABytmdspEDcHRdP3QKG9zl4hKKfKeAPVd68KLD145ozqOpHnmdI2FScBCNwTk6hLVrLlp5+jXcd0OhcblIMi6n56HCw5NJtn3UDOmtBuRf4kzWPnoAsHqBzKkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbd9uHXZaGT2cvhRs7reawctIXtX1s3kTqM9YV+/wCpBpuIV/6rgYT7aH9jRhjANdrEOdwa6ztVmKDwAAAAAAEGp9UXGSxcUSGMyUw9SvF/WNruCJuh/UTj29mKAAAAAPVoKwb8y9umtA0jShSx996di14R5FpyvKqSYj8+Z3objJclj04kifG7PRApFI4NgwtaE5na/xCEBI572Nvp+Fm7HPCjKxncvtY5by6WcW0F9RHewB0PZf11ht1kRKpNj+W0sDENeym+1JDNRCeZ7VTDsuaSdPoO++Usgv8F2mApbf4WPUsPNsn6+Yv59ZOc5qy/EPSN8y/0rNX75XdiHVbNDrwdm/rd1skt4FKR1S97OZKYlNAN73RBtoNNsze+RPxsTu9AoGHaaRZIoOWm2TjN1v1YB76t2945o/r5lH7y8R3lfECU5wfDMxdFxDdAnxPJvo9e70QJzf/bVCAUVmkECwIAAXwDAAAAXvxYX38aix411zG+PoOUNq9s23uIAsQYLzazqnEJxE0gAAAAAAAAADQzMTZuMnF0bWc5eXVDMWZBTkJGTU1IQXc4Znk0TVpp2CEfAAAAAAClAAAAAAAAAAbd9uHXZaGT2cvhRs7reawctIXtX1s3kTqM9YV+/wCpDAQBDQAOAQEPFQwQCw4CEQMEEg0FBgcTCBQVAAkBChoB/AAAAAAAAAAA6AMAAAAAAADoAwAAAAAAAAwDAQAAAQkA'
],please help me~

**Comment by cruzshia** [comment]
looks like market with WSOL mint might cause unexpected error in devnet, so I suggest you create a new devnet mint (here: https://coinfactory.app/generator/solana/spl-token) and create a new market without WSOL mint then create pool will go through. (there's no such error in mainnet)

**Comment by cruzshia** [comment]
and also use createMarket.ts in demo code to create market as well(which will initialized new market)

**Comment by cruzshia** [comment]
after doing more testing, there're some points should notice:
1. if want to create devent Amm pool in raydium, use createMarket.ts in demo repo to create market
2. if your devent market contains SOL/WSOL mint, please ensure your amount should >= 4*10**9(4 sol) or you might encounter lp_amount not enough error

**Comment by cruzshia** [comment]
more updates: 
there's a bug in serum create devnet market https://serum-explorer.vercel.app/market/create?network=devnet,
which they used wrong program id...that's why you got this error, so please follow steps I mentioned previously and it will go through.
