### ISSUE TITLE
 withdrawLiquidity.ts to remove Liquidity get error

### ISSUE THREAD

**Issue by chatTeap** [raydium-io/raydium-sdk-V2-demo#38]
When I  using withdrawLiquidity.ts to remove Liquidity, how do I set the value of inputAmount?
 if I want to remove 100% of the liquidity? I am querying my Token Unstaked Liquidity=98009999 on Raydium V3 UI, token decimal=3, when I set inputAmount to 98009999000 I get error> Program log: Error. insufficient funds; Where is this problem?

**Comment by cruzshia** [comment]
code below can confirm you lp balance (r.amount), please confirm
```
await raydium.account.fetchWalletTokenAccounts()
const r = raydium.account.tokenAccounts.find((p) => p.mint.toBase58() === poolInfo.lpMint.address)
 r?.amount
  ```

**Comment by chatTeap** [comment]
> code below can confirm you lp balance (r.amount), please confirm
> 
> ```
> await raydium.account.fetchWalletTokenAccounts()
> const r = raydium.account.tokenAccounts.find((p) => p.mint.toBase58() === poolInfo.lpMint.address)
>  r?.amount
> ```

He's running fine now. Thank you.
