### ISSUE TITLE
unwrap many account

### ISSUE THREAD

**Issue by BobosanCrypto** [raydium-io/raydium-sdk-V2-demo#39]
i use cpmm baseout, but wsol creates many accounts

![Screenshot 2024-06-18 092159](https://github.com/raydium-io/raydium-sdk-V2-demo/assets/171489804/2d80d5d1-e86e-4ef6-89f0-913ce83f01a1)

**Comment by cruzshia** [comment]
Could you provide txIds?

**Comment by BobosanCrypto** [comment]
i use createAndSendV0Tx(builder.AllTxData.instructions)

**Comment by cruzshia** [comment]
I tested it with swap function and it works well, so I need txid to check what' going on.

**Comment by BobosanCrypto** [comment]
https://solscan.io/tx/NMgV6gn7er8H6yb9pxZUwTeoCvmV62jZqAoBrJj7LpSX5avqLpZgGNixTAxMMJdXWBwoEm8xDtG8dpgFUCw3ZYu

**Comment by cruzshia** [comment]
fix has been pushed to master, pull and run yarn install to update sdk

**Comment by BobosanCrypto** [comment]
ok thanks

**Comment by BobosanCrypto** [comment]
one question, how to combine clmm with cpmm in one transaction? too large data

**Comment by cruzshia** [comment]
you can take a reference to sdk txTool, but you need to check duplicated token account creation..etc
https://github.com/raydium-io/raydium-sdk-V2/blob/master/src/common/txTool/txTool.ts#L789
https://github.com/raydium-io/raydium-sdk-V2/blob/master/src/common/txTool/txTool.ts#L607

**Comment by BobosanCrypto** [comment]
Thank you very much
