### ISSUE TITLE
Frequent RPC Node Timeout Issue When Sending Transactions

### ISSUE THREAD

**Issue by miaoluyao** [raydium-io/raydium-sdk-V2-demo#40]
I am encountering an issue with RPC node timeouts when frequently sending transactions. I am currently developing a market cap management tool, and during this process, the getBlockHeight method is called very frequently. I would like to know how to modify the frequency of these calls to prevent the RPC node timeouts.

**Comment by cruzshia** [comment]
if you frequently send transactions there'e no way to optimize it, block height grows by time, the best way is to reduce sending frequency
