### ISSUE TITLE
Program returned error: exceeded CUs meter at BPF instruction

### ISSUE THREAD

**Issue by BobosanCrypto** [raydium-io/raydium-sdk-V2-demo#42]
i try trade, routeSwap. 
https://solscan.io/tx/4Pni1hcTn9RpPqEP5wkb9NxhovsZv7dXvdRb4aoTRhCPkmZgzRZCtd35aybNrqXxb2FywfvSWGrk18yujsveA8Wb

**Comment by cruzshia** [comment]
routeSwap will update to new version later or so, please try after we got update

**Comment by BobosanCrypto** [comment]
ok, Thank You

**Comment by BobosanCrypto** [comment]
Does routeSwap work for transactions like this?
https://solscan.io/tx/2LPL7NVS2FxRTd24QsFWxoqLN9agjJCZgxeyENB4RQfHv4LKZngHmdhuBGeyj8WpS7Wc6pirREneF89gp9DLfDhb
