### ISSUE TITLE
Getting authority error while call addLiqudity function on devnet.

### ISSUE THREAD

**Issue by Sky1706** [raydium-io/raydium-sdk-V2-demo#49]
Error: Error adding liquidity: TypeError: Cannot read properties of undefined (reading 'authority'),

  const { execute, extInfo } = await raydium.liquidity.addLiquidity({
            poolInfo: poolInfo,
            amountInA: new TokenAmount(
                toToken(poolInfo.mintA),
                new Decimal(inputAmount)
                    .mul(10 ** poolInfo.mintA.decimals)
                    .toFixed(0),
            ),
            amountInB: new TokenAmount(
                toToken(poolInfo.mintA),
                new Decimal(r.maxAnotherAmount.toExact())
                    .mul(10 ** poolInfo.mintA.decimals)
                    .toFixed(0),
            ),
            fixedSide: 'a',
            txVersion: TxVersion.LEGACY,
            payer: owner.publicKey,
   });
   
               marketId: 'FZNPdpkQjRvaxDjQvs1VETGkQ2ShxdpuakZXeuf4ZWdw',
            configId: '8QN9yfKqWDoKjvZmqFsgCzAqwZBQuzVVnC388dN5RCPo',
            programId: 'HWy1jotHpo6UqeQxx49dpYYdQB8wj9Qk9MdxwjLvDHB8',
            signer: "4GMb3ucYaXLvySAFuMBjnBSh6KqKnFcaJqaHqWUFhThT"
            poolId: "3uVW9GBTTSZjqR53y9HYo8KYDqTxC9pxcqDPAjhsLdJR"
            
   I am manually passing pool info by creating an object for pool info with the required details and now I am getting an authority error.

**Comment by cruzshia** [comment]
master branch just pushed devnet example earlier, please take a reference: https://github.com/raydium-io/raydium-sdk-V2-demo/blob/master/src/amm/addLiquidity.ts#L29 in case you missed any required pool info

**Comment by Sky1706** [comment]
Actually devnet function are only supported with raydium SDKV2 0.1.25-alpha version not and I am using ^0.1.9-alpha.

**Comment by cruzshia** [comment]
so, just upgrade the sdk.

**Comment by Sky1706** [comment]
okay let me check with SDKV2 0.1.25-alpha version.
