### ISSUE TITLE
Fix problem in `calc AmountOut`

### ISSUE THREAD

**Issue by kasrakhamesi** [raydium-io/raydium-sdk-V2-demo#5]
in this : https://github.com/raydium-io/raydium-sdk-V2-demo/issues/4

my first issue is fixed and thanks a lot

about second issue,can you write script in this raydium-sdk-v2-demo to calculate amount Out like raydium UI ? 
I need it,or send doc to me ? I can't find any good docs, I check frontend source code but can't help  me

**Comment by cruzshia** [comment]
as I said, sdk V3 didn't support swap feauture like UI, if you still want to get amount like UI, please follow v1 sdk version.
https://github.com/raydium-io/raydium-sdk-V1-demo/blob/master/src/swapRoute.ts
