### ISSUE TITLE
I don't want to use sendAndConfirmTransaction for swapping

### ISSUE THREAD

**Issue by miaoluyao** [raydium-io/raydium-sdk-V2-demo#50]
I don't want to use sendAndConfirmTransaction for swapping. Can I use sendTransaction to send the transaction instead, so that it just broadcasts the transaction and does not wait for it to confirm on the network?

**Comment by cruzshia** [comment]
swap function returns `transaction`, you can use it to do whatever you want to send tx and don't have to call `execute`, and of course, you have to sign it by yourself

**Comment by cruzshia** [comment]
just updated sdk in demo repo and it uses sendTransaction instead of sendAndConfirmTransaction.

**Comment by miaoluyao** [comment]
Thank you！
