### ISSUE TITLE
yarn dev src/trade/routeSwap.ts, the txIds always wrong

### ISSUE THREAD

**Issue by YoungHorn1999** [raydium-io/raydium-sdk-V2-demo#58]
yarn dev src/trade/routeSwap.ts, and set sequentially: false, the txIds always like this:
<img width="930" alt="截屏2024-07-11 18 00 46" src="https://github.com/raydium-io/raydium-sdk-V2-demo/assets/39025558/a0b4f95a-752a-4147-8116-b7ac64df3319">

**Comment by junhoyeo** [comment]
@YoungHorn1999 I downgraded to `0.1.21-alpha` and it seems like it's working again

```json
    "@raydium-io/raydium-sdk-v2": "0.1.21-alpha",
```

**Comment by YoungHorn1999** [comment]
> @YoungHorn1999 I downgraded to `0.1.21-alpha` and it seems like it's working again
> 
> ```json
>     "@raydium-io/raydium-sdk-v2": "0.1.21-alpha",
> ```

thankyou so much bro, it works now
it seems like the newest version in routeSwap.ts have some bug

**Comment by cruzshia** [comment]
will fix this issue in later version, will keep you posted in this thread

**Comment by cruzshia** [comment]
fixed in latest version 0.1.39-alpha

**Comment by junhoyeo** [comment]
yeee thanks
