### ISSUE TITLE
has expired: block height exceeded. How can I set the prioritization fee?

### ISSUE THREAD

**Issue by miaoluyao** [raydium-io/raydium-sdk-V2-demo#6]
When I run `yarn dev src/swap.ts`, I encountered the following error. I suspect it's due to insufficient prioritization fee. How can I set the prioritization fee?

`yarn run v1.22.21
$ ts-node src/amm/swap.ts
simulate tx string: [
  'AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAQAGFGBXSj7I1ZOdVdY9p0N6d4tz+srdKAqRB3AIyRutEkKQk9SqUEHu/e3mZ+DGO/I+OMzXOBuqkKn2oVz+ZTl4y5KypEYsshQ/KAA/HjvkHcxzz+n9c39GYdYM+0f4ZR/iQ1FnvAnuQrROrKLNhrbniItgRDdixq8YXHaF3/TJJKG/qeUBGuk40vXmdKn1Y+2NiC+f6/zXjVha8efEcP3G5gkm3v5YwWlcbM0FnyUklfSsj1mroP6huK/duAujunwJ0tluoxnY7jYlB+t+7BbEV1TgQTi1T0A6QXvVkPErJ/aWzawDCFqf5dNFGW2tcli44G633igQL3UjSAXefy7jZ5u6rv8cl4ZIZeEMp7IU666lC+lbTdMM1WXPNFXX+vSULgLztVBnGfX0a5xP1ArI5r64lGlRl4DKc1HjdqK0xlbgEHFwLBRgfgCuOhwLabdTypg6RjPhvn4zmlKx66sKC8TMQOZIqeWuuGiRKIyeYCM1bfBu3hXknv4ypbzHwaSyCmYuaCbbrH1+vD22cUZMqD3xBHXSs3yECnkctA+mzCVYw8j8DxRtRDrr68dPzYC3qp5oPlEQbm+j614JZOPKKQOMlyWPTiSJ8bs9ECkUjg2DC1oTmdr/EIQEjnvY2+n4WTeZjMvy0EWLYVy8xrGjZ8R0np/vcwZiLhsbWJEBILyaxvp6877brTo9ZfNqq8l0MbG75MLS9uDkfKYCA0UvXWFL2UnENgLDPyB3kO0Wo1JMobmXXPEhoqkM/+x9+LaKzUFXsFgPMcX85EpiWC28+deO51lDoISjk7NQNo0iiZMI9dfug9Jb5P3YnqDw/DyruHiSnwwES9lmpl3OjIA6PltD1Mjd+HIiiDBibQodwRbrrh3XK3/bzsnerBy8uMAhqAMOBgABAA8UFQAOBgACABAUFQAREhUDEgQFBgcWCAkKCwwNEwECABEJECcAAAAAAAAVRgAAAAAAAAEZjx9MOkUiY9QTss0X68vBoOWIc2TmJhoSqBeS6hZaPgADAAIL'
]
/Users/xxxx/Desktop/solana/raydium-sdk-V2-demo/node_modules/@solana/web3.js/src/connection.ts:3957
        throw new TransactionExpiredBlockheightExceededError(signature);
              ^
TransactionExpiredBlockheightExceededError: Signature 5A4RNPE5eXoDFKowvzK48R2umfLMsewKaduds4v5VpGf9Y1TV1qxMa8mgbXTFZSHRrJipJUpr4VRtikNGTQ4w2g8 has expired: block height exceeded.
    at Connection.confirmTransactionUsingBlockHeightExceedanceStrategy (/Users/xxxx/Desktop/solana/raydium-sdk-V2-demo/node_modules/@solana/web3.js/src/connection.ts:3957:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Connection.confirmTransaction (/Users/xxxx/Desktop/solana/raydium-sdk-V2-demo/node_modules/@solana/web3.js/src/connection.ts:3768:14)
    at async execute (/Users/xxxx/Desktop/solana/raydium-sdk-V2-demo/node_modules/@raydium-io/raydium-sdk-v2/src/common/txTool/txTool.ts:423:11) {
  signature: '5A4RNPE5eXoDFKowvzK48R2umfLMsewKaduds4v5VpGf9Y1TV1qxMa8mgbXTFZSHRrJipJUpr4VRtikNGTQ4w2g8'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by cruzshia** [comment]
you can pass computeBudgetConfig param to swap method
```
const { execute } = await raydium.liquidity.swap({
    poolInfo,
    amountIn: new BN(amountIn),
    amountOut: out.amountOut,
    fixedSide: 'in',
    inputMint: poolInfo.mintA.address,
    associatedOnly: false,
    txVersion,
    // set you priority fee here
    computeBudgetConfig: { 
      units: 6000,
      microLamports: 100000000,
    },
  })
  ```
