### ISSUE TITLE
Program Error: "Instruction #3 Failed - The program expected this account to be already initialized"

### ISSUE THREAD

**Issue by YoungHorn1999** [raydium-io/raydium-sdk-V2-demo#61]
I run yarn dev trade/routeSwap.ts, swap 3B5wuUrMEi5yATD7on46hKfej3pfmd7t1RKgrsN3pump to SOL, the tx is on chain, and the code don't throw error, but the solscan always show this error: 
Program Error: "Instruction #3 Failed - The program expected this account to be already initialized"
how can I make the tx success
![WechatIMG513](https://github.com/user-attachments/assets/dc068482-e976-4a5b-b511-067593867a0c)

**Comment by cruzshia** [comment]
update sdk to `0.1.40-alpha` should work, pushed to master

**Comment by YoungHorn1999** [comment]
It seems like there is not have the 0.1.40-alpha yet?
<img width="542" alt="截屏2024-07-13 14 02 10" src="https://github.com/user-attachments/assets/f98493fb-a904-490c-84fe-fc3ffe24a57e">

**Comment by cruzshia** [comment]
https://github.com/raydium-io/raydium-sdk-V2-demo/commit/719eaf4d92295d6d26530d58b509a429868b012b

**Comment by YoungHorn1999** [comment]
> [719eaf4](https://github.com/raydium-io/raydium-sdk-V2-demo/commit/719eaf4d92295d6d26530d58b509a429868b012b)

thank u so much, it works for almost token now.
I meet a new error in routeSwap, when I swap BdV3mqyMwwy7NiFS7pY45qz18zcQTF5xjRQWLsscrtqp to sol by the routeSwap, found 1 pool, but the code throw error show there don't have route
![WechatIMG514](https://github.com/user-attachments/assets/6c4fed59-a9e3-4641-9162-596c8fa06086)

**Comment by cruzshia** [comment]
please upgrade sdk to version `0.1.42-alpha` and see code below to set log visible, I added some logs to show what happened.
this error might caused by input amount too small (makes output amount to 0) or insufficient pool liquidity.
you can upgrade sdk and set larger input amount and try again.
https://github.com/raydium-io/raydium-sdk-V2-demo/commit/9bc0d2da9e8a7093e326994bb446182884d0c148#diff-1cccd777077d6bd8943af4b047c4edd63f9c08d450ea1c051d4f73d55b6ca429R27

**Comment by YoungHorn1999** [comment]
after upgrade, I swap the token BdV3mqyMwwy7NiFS7pY45qz18zcQTF5xjRQWLsscrtqp and the value is 0.000123u, why it deposit 1sol to create token account, it's too much, it seems like have some problem?
![WechatIMG516](https://github.com/user-attachments/assets/07ddd9da-01f0-4a60-8b10-34d6610be3cd)

**Comment by cruzshia** [comment]
Please provide txId

**Comment by YoungHorn1999** [comment]
3M5EhdzFBkpXjnME3hT8JtFhXEVQ7uJ3w8NHzwQ5muZB7oCNrxNaHJASL9BFPr1VMsoERHQaAUhh8mnRAsPtcg69

**Comment by YoungHorn1999** [comment]
Normally, it should only deposit 0.002SOL to create token account, but it deposit 1SOL

**Comment by cruzshia** [comment]
It’s solscan display issue, this tx didn’t charge 1 sol, check other explorer here https://explorer.solana.com/tx/3M5EhdzFBkpXjnME3hT8JtFhXEVQ7uJ3w8NHzwQ5muZB7oCNrxNaHJASL9BFPr1VMsoERHQaAUhh8mnRAsPtcg69

**Comment by cruzshia** [comment]
In summary mode display correctly
![image](https://github.com/user-attachments/assets/5fc57101-fe07-49de-bd71-cdf2039d6024)

**Comment by YoungHorn1999** [comment]
I think there have a bug causes the deposit amount to be proportional to the transaction amount. When the money in the wallet is less than the deposit amount, the transaction will fail. 
the tx in the pic is 4uxNNxXQfzKNBgWUHkUJfGpT6Dp2tmgWfsESiha5fcVUS6fucrqzMvgPn5uVxgcBeErV6BC7SzHhsFWmy1r4hid9
![1721046018409](https://github.com/user-attachments/assets/1d340b41-966e-477d-aa1b-865e11eaf0a6)
