### ISSUE TITLE
Input token account not found - no way to generate associated account during swap

### ISSUE THREAD

**Issue by gladwinput** [raydium-io/raydium-sdk-V2-demo#62]
Error: [\"input token account not found\"]

    await raydium.liquidity.swap({
      poolInfo,
      poolKeys,
      amountIn: new BN(amountIn),
      amountOut: out.minAmountOut,
      fixedSide: 'in',
      inputMint: mintIn.address,
      txVersion: txVersion,
      config: {
        inputUseSolBalance: true,
        outputUseSolBalance: true,
        associatedOnly: false,
      },
    });

If you try to fire off a swap there's 1) no way to put a custom instruction to create the token and 2) if you try to create it to get the instruction to put it into a new transaction you setup with the custom instruction first it'll fail its check on swap anyway.
    
Possible to just get a flag to set up an associated token?

**Comment by cruzshia** [comment]
input token account not found means you don't have the token account you want to input,
what's your wallet address and swap mint address?

**Comment by cruzshia** [comment]
`const { execute, transaction, builder } = await raydium.liquidity.swap` return transaction and all instructions in builder `builder.allInstructions`, you can build your own tx by combine these data, just ensure you have input mint balance(token account) before swap

**Comment by gladwinput** [comment]
Is there any way to suppress the errors though? because it throws them no matter what so you can't get the variables back

**Comment by cruzshia** [comment]
as I said previous, sent a small input mint amount to your wallet, it will create token account for you.
you can't make swap tx without input mint token account.

**Comment by gladwinput** [comment]
but that's the problem - I need the instruction ready so that when the amount comes to the wallet I can create the swap. But I need to use this swap() to create the instruction.
I would have to buy the input amount in another transaction with sol to get the token to then create this transaction to sell it, doesn't make sense

**Comment by cruzshia** [comment]
maybe you should fork our sdk and customize by yourself. 
validation code is here: https://github.com/raydium-io/raydium-sdk-V2/blob/master/src/raydium/liquidity/liquidity.ts#L870
we can't skip this check just for special cases.

**Comment by cruzshia** [comment]
modify name/version in package.json and run `yarn push` will push sdk to npm regiestry, and of course you need to register a npm account (https://www.npmjs.com/), then you can run yarn install to get your customized package.
if you just want to build, just run `yarn build` and you can find compressed index.js in dist directory

**Comment by gladwinput** [comment]
Appreciate you going out of your way to respond so helpfully
