### ISSUE TITLE
when deposit sol to create token account, the amount is wrong

### ISSUE THREAD

**Issue by YoungHorn1999** [raydium-io/raydium-sdk-V2-demo#63]
when swap this token BdV3mqyMwwy7NiFS7pY45qz18zcQTF5xjRQWLsscrtqp to the sol.
the deposit amount to be proportional to the transaction amount. When the money in the wallet is less than the deposit amount, the transaction will fail. If it's sloscan display bug, the tx will not fail.
the tx in the pic is 4uxNNxXQfzKNBgWUHkUJfGpT6Dp2tmgWfsESiha5fcVUS6fucrqzMvgPn5uVxgcBeErV6BC7SzHhsFWmy1r4hid9

![1721046018409](https://github.com/user-attachments/assets/96bd12a9-4667-478d-9c1b-26d520b88dc5)

**Comment by cruzshia** [comment]
update sdk and try again https://github.com/raydium-io/raydium-sdk-V2-demo/commit/69a813fe31541d648a2c650253d533137d504d1a

**Comment by YoungHorn1999** [comment]
thank you so much. it's ok.
