### ISSUE TITLE
Getting "429: Too Many Requests" error

### ISSUE THREAD

**Issue by tushar-sahoo** [raydium-io/raydium-sdk-V2-demo#64]
```
raydium = await Raydium.load({
    owner,
    connection,
    cluster,
    disableFeatureCheck: true,
    disableLoadToken: !params?.loadToken,
    blockhashCommitment: 'finalized',
    // urlConfigs: {
    //   BASE_HOST: '<API_HOST>', // api url configs, currently api doesn't support devnet
    // },
  })
```

Does this method call Raydium API? If yes is there any way to get this object without the API call. Also, if there is some premium service available that removes the API call limit that would be great.

Also is it possible to create a common raydium object and then use the raydium.setOwner function to change the owner while performing swaps.

**Comment by cruzshia** [comment]
no, there's no way to remove rate limit at this moment.
and yes, you can use raydium.setOwner to change owner while programming

**Comment by tushar-sahoo** [comment]
Ok thanks @cruzshia. Works good now.
