### ISSUE TITLE
Token-2022 Program Support - Urgent please - Held project

### ISSUE THREAD

**Issue by magnomilk100** [raydium-io/raydium-sdk-V2-demo#66]
Hi team,

I have tried to get information looking at the project, release notes or so on, but I could not find anything. Would you be so kind to inform me if this project is supporting Token-2022 Program for creating Market Id?
My goal is to create the openbook and create the liquidity pool on Raydium, can I do both of this code? Or they are two complete different things... I have to find another use another library for Market Id and for creating the liquidity pool on Raydium.
I am using Token-2022 Id program... I have tried src/amm/createMarket.ts but I get an error saying 
[Unknown Program (EoTcMgcDRTJVZDMZWBoU6rhYHZfkNTVEAfz3uUJRcYGj) Instruction](https://explorer.solana.com/tx/3e6QxxCK89od9U7vzW4nXqpznqfRjpcPB7XVSpiRM8SLnFxmF6tTGXStJ3HTNww9haQuHEqJy2mhR4qjM2yYNTq9?cluster=devnet#ix-3)
> Program consumed: 2890 of 599700 compute units
> Program returned error: "custom program error: 0x1000694"

This is the MarketID in question:   DEPJttbs7VhBJvonmjdBA5iNVoEQdaWRZFyzZaLLVCVH

Thanks for any input on it... Have a great day.

**Comment by magnomilk100** [comment]
I am able to create the Market Id with createMarket.ts, when I use the data from the market id on createAmmPool.ts, I get the following message: you don't has some token account

**Comment by cruzshia** [comment]
amm pool doesn't support token-2022, if you want to create pool with token-2022 mints, use src/cpmm/createCpmmPool.ts instead.
