### ISSUE TITLE
For Market ID, Shall I use OpenBook Dex or createMarket.ts script here? Please... And the Market Id is also restricted by PROGRAM_ID?

### ISSUE THREAD

**Issue by magnomilk100** [raydium-io/raydium-sdk-V2-demo#67]
Hi,
Thanks for the reply in the other ticket, what helped me a lot... Thanks so much for any reply on this question...

First question please:
For Market ID, Shall I use OpenBook Dex or createMarket.ts script here? Please... And the Market Id is also restricted by PROGRAM_ID?

I have lately used the createMakert.ts here and used also the createAmmPool.ts, both using the regular PROGRAM_ID. I have now 2 projects, 1 with PROGRAM 2022 and the other with the Regular...

Using the createMarket.ts with the Regular worked perfectly, I got a marketId and looking at the transactions seems to be all good... then tried to use the createAmmPool and then get the following error 
**error = TransactionExpiredBlockheightExceededError: Signature 49P7We74hF72eiAVd3TYpo4XEwvzM3EvtQCryN9wD5VTWXzHBZui98a6283J49J198E6HjLhYFnrxAe8VXrGdxf2 has expired: block height exceeded.**

I have resherched a lot, but not sure why... changed several things, changed also values for basemint and quotemint, I have on test 80 SOL... No idea... Kindly help me on that.

By the way, I have tried to use Discord, por 2 times, using my account and my wife's one, when we post the query, asking something, we get TIMED OUT. So, no chance to ask anything there, I am obligated to use this channel only!

**Comment by cruzshia** [comment]
please use createMarket.ts as I mentioned in readme https://github.com/raydium-io/raydium-sdk-V2-demo?tab=readme-ov-file#create-amm-pool-error.
as I said please do not use 2022 program to createAmmPool.
and please ensure you are using correct devnet programId.
in createMarket `dexProgramId: DEVNET_PROGRAM_ID.OPENBOOK_MARKET` and in createAmmPool use 
`programId: DEVNET_PROGRAM_ID.AmmV4`,  marketInfo `DEVNET_PROGRAM_ID.OPENBOOK_MARKET`, feeDestinationId  `DEVNET_PROGRAM_ID.FEE_DESTINATION_ID`

**Comment by magnomilk100** [comment]
I will try, thanks so much Shia for your kindness!
