### ISSUE TITLE
My transaction reported an error

### ISSUE THREAD

**Issue by miaoluyao** [raydium-io/raydium-sdk-V2-demo#7]
`yarn dev .\src\amm\swap.ts`

txid：`https://solscan.io/tx/5bRpSutAuqGJwGHvi8eAX9HSJ7dwejbAMMGfnZsZGvSeCphHxrktFhgasMMzPiqPypTaWY33oVdZbjFCxMP4Q2Da`

**Comment by cruzshia** [comment]
please try set higher priority fee and increase slippage, it will go through smoothly.
just try a swap RAY -> USDC and it works well
