### ISSUE TITLE
Slow swap method

### ISSUE THREAD

**Issue by gladwinput** [raydium-io/raydium-sdk-V2-demo#70]
```
 const { transaction } = await raydium.liquidity.swap({
                    poolInfo,
                    poolKeys,
                    amountIn: new BN(frontAmount),
                    amountOut: out.minAmountOut,
                    fixedSide: 'in',
                    inputMint: frontInputMint,
                    txVersion: TxVersion.V0,
                });
```

Running this and it takes 600ms to run (tried multiple private RPCs this is about average). It's not clear what slows it down so much. maybe the address lookup cache? That's insanely slow. Is there some way to cache aspects of it or speed up this swap transaction at all?

**Comment by cruzshia** [comment]
after test, it works well in my side(within 10 seconds to complete tx), if you are saying waiting for tx confirmation, please set up higher `computeBudgetConfig`
<img width="989" alt="image" src="https://github.com/user-attachments/assets/6f0f4253-db13-4484-9ba9-0f838d911cd1">
