### ISSUE TITLE
error=Error processing Instruction 5: custom program error: 0x1770

### ISSUE THREAD

**Issue by Sky1706** [raydium-io/raydium-sdk-V2-demo#71]
I am facing a 0x1770 error code while performing the CPMM swap function on the Mainnet, but the same swap function works fine on the devnet.

**Comment by cruzshia** [comment]
could you provide txid?

**Comment by error1001es** [comment]
> could you provide txid?

https://explorer.solana.com/tx/4ZibNv75fRhgtuReB42fsckwQYu5dtwkLuJ2Hngtcqnck2bSVSToWSVtz5hLfNEYAEy2vgpPcNJhwhQLaGfZYDLu?cluster=devnet
