### ISSUE TITLE
Token creation.

### ISSUE THREAD

**Issue by vikito755** [raydium-io/raydium-sdk-V2-demo#73]
Hello, while developing on the devnet.

I stumbled into the issue of not being able to create a CLMM Pool over and over for testing.

To solve it I wrote a small utility function to create a new that makes and mints tokens. Would you mind if I make a pull request adding the utility function and using it in "createPool"? 

P.S: The "RAY" token example will still be there, as a I realise it is a branding move.

**Comment by cruzshia** [comment]
I think you can just put this util function into src/test/xx.ts only, and it will not be affected by repo's code :)

**Comment by vikito755** [comment]
There may have been a misunderstanding.

I found the utility function in question instrumental to easily run "createPool". With it I got an error that the tokens are already used (which makes sense).

I am asking if it is okay to make a pull request with that function so the example is (in my opinion) a bit easier to use.

If it is not a welcome contribution, I understand.

**Comment by cruzshia** [comment]
I think we should keep createPool simple but not includes other features(like create mints) which should be done by user before running scripts.
and for sure, thanks for your advise and contribution :)
