### ISSUE TITLE
FetchPoolById return null for new created pools

### ISSUE THREAD

**Issue by dexweb3** [raydium-io/raydium-sdk-V2-demo#74]
I don't know why but pools that was created 1-10 min ago return null at "fetchPoolById" from Raydium api

Looks like only after 10 and more minutes it start return data (but this pull already exist and trades works at market on real time)

Is it possible to fix it?
 
<img width="707" alt="image" src="https://github.com/user-attachments/assets/c648cb97-44d1-47e9-8e2e-99bd43394603">

**Comment by cruzshia** [comment]
FYI: https://github.com/raydium-io/raydium-sdk-V2-demo/issues/65
