### ISSUE TITLE
Failed to create the Market ID.

### ISSUE THREAD

**Issue by AphobiaCat** [raydium-io/raydium-sdk-V2-demo#76]
I followed cruzshia's advice and used the two mint addresses already created in dev net as baseInfo and quoteInfo, with a Block height exceeded. The problem.
  pls help, thanks!

```javascript
async createMarket() {
  let base_token = new PublicKey('E5gYGvqxYvRJEGd51dQqsXPdti3YXnFyXtb4JSkuM8kc');
  let quote_token = new PublicKey("E3QZcRgZrvG2QtBZCEGuPf9ctDGrRs8WgWQBdzy8ZjpF");
  const raydium = await initSdk()
  
  // check mint info here: https://api-v3.raydium.io/mint/list
  // or get mint info by api: await raydium.token.getTokenInfo('mint address')
  
  const { execute, extInfo, transactions } = await raydium.marketV2.create({
	  baseInfo: {
		  mint: base_token,
		  decimals: 9,
	  },
	  quoteInfo: {
		  mint: quote_token,
		  decimals: 9,
	  },
	  lotSize: 1,
	  tickSize: 0.01,
	  // dexProgramId: OPEN_BOOK_PROGRAM,
	  dexProgramId: DEVNET_PROGRAM_ID.OPENBOOK_MARKET, // devnet
  
	  // requestQueueSpace: 5120 + 12, // optional
	  // eventQueueSpace: 262144 + 12, // optional
	  // orderbookQueueSpace: 65536 + 12, // optional
  
	  txVersion,
	  // optional: set up priority fee here
	  computeBudgetConfig: {
			  units: 600000,
			  microLamports: 100000000,
	  },
  })
  
  console.log(
	  `create market total ${transactions.length} txs, market info: `,
	  Object.keys(extInfo.address).reduce(
		  (acc, cur) => ({
			  ...acc,
			  [cur]: extInfo.address[cur].toBase58(),
		  }),
		  {}
	  )
  )
  
  const txIds = await execute({
	  // set sequentially to true means tx will be sent when previous one confirmed
	  sequentially: true,
  })
  
  console.log('create market txIds:', txIds)
}
```

**Comment by cruzshia** [comment]
maybe you should check your rpc config and set raydium cluster to devnet in config.ts.
after test sdk works well as usual

**Comment by cruzshia** [comment]
and the mints you used for create market, their supply looks like to be zero for both...
https://explorer.solana.com/address/E5gYGvqxYvRJEGd51dQqsXPdti3YXnFyXtb4JSkuM8kc?cluster=devnet
https://explorer.solana.com/address/E3QZcRgZrvG2QtBZCEGuPf9ctDGrRs8WgWQBdzy8ZjpF?cluster=devnet

**Comment by cruzshia** [comment]
here's a normal txs should be

https://explorer.solana.com/tx/31uiEvC14PR4comSLeVt236kgeE1B7sn2EFLAJonHzZHVKQpRNaiUkYkonRMoYs7JGMpe7AvTZZVVLpQVqUKVam5?cluster=devnet
https://explorer.solana.com/tx/4rH3dkoPVPRdehHpxTghAxN1NkcyLwgj8Eam2R47L8YdZDw6jjgC4JV5XyHgd5A3N76RPhHQGjyScRtobfcZfALd?cluster=devnet

mints should have supply and have some balances in your devent wallet
<img width="1200" alt="image" src="https://github.com/user-attachments/assets/ae220b24-ffbc-45d9-8c43-01355d11b41b">
<img width="1178" alt="image" src="https://github.com/user-attachments/assets/1364215d-6a4d-457a-982b-9f83f705312d">

**Comment by AphobiaCat** [comment]
> here's a normal txs should be
> 
> https://explorer.solana.com/tx/31uiEvC14PR4comSLeVt236kgeE1B7sn2EFLAJonHzZHVKQpRNaiUkYkonRMoYs7JGMpe7AvTZZVVLpQVqUKVam5?cluster=devnet https://explorer.solana.com/tx/4rH3dkoPVPRdehHpxTghAxN1NkcyLwgj8Eam2R47L8YdZDw6jjgC4JV5XyHgd5A3N76RPhHQGjyScRtobfcZfALd?cluster=devnet
> 
> mints should have supply and have some balances in your devent wallet <img alt="image" width="1200" src="https://private-user-images.githubusercontent.com/6680106/359760687-ae220b24-ffbc-45d9-8c43-01355d11b41b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMjAxNTYsIm5iZiI6MTcyNDIxOTg1NiwicGF0aCI6Ii82NjgwMTA2LzM1OTc2MDY4Ny1hZTIyMGIyNC1mZmJjLTQ1ZDktOGM0My0wMTM1NWQxMWI0MWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjFUMDU1NzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQyZjAzMzI4NDY0M2RjMDE1YzMzOTI4MDhhY2MzZmEyNzMxZTJkZjAyODUwYjA4NmY3MDFkMjg1ZDVkOTU5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PMAqjNDtN6u1p3BMFnbsE0wcCK7hItslxG3WMdGKf4A"> <img alt="image" width="1178" src="https://private-user-images.githubusercontent.com/6680106/359760715-1364215d-6a4d-457a-982b-9f83f705312d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMjAxNTYsIm5iZiI6MTcyNDIxOTg1NiwicGF0aCI6Ii82NjgwMTA2LzM1OTc2MDcxNS0xMzY0MjE1ZC02YTRkLTQ1N2EtOTgyYi05ZjgzZjcwNTMxMmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjFUMDU1NzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODcwNDc4MWJiODhiMDU4MjJkNTliYTkwMGE5YjhhODYxNzUwNGJmOGFmOGIyNThlYzU4MzcwZjRhNjE3MzI4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HtToWdslv3vgFAbhQnuMNDBofy9vZnikKG1cOmc8lFw">

Oh ok, I thought I needed to increase the supply when creating amm pool. I will try again, thank you
