### ISSUE TITLE
Transaction overlimit when add computeBudgetConfig 

### ISSUE THREAD

**Issue by dexweb3** [raydium-io/raydium-sdk-V2-demo#8]
https://github.com/raydium-io/raydium-sdk-V2-demo/blob/2d867119dae1afbc33f6438ec9f5a2e0fa981c75/src/amm/createMarket.ts#L24

When I uncomment it I got:
ERROR [ExceptionsHandler] failed to send transaction: base64 encoded solana_sdk::transaction::versioned::VersionedTransaction too large: 1684 bytes (max: encoded/raw 1644/1232)

How that possible to solve it? 

**My config for devnet trx:**
`{
  baseInfo: {
    mint: PublicKey [PublicKey(So11111111111111111111111111111111111111112)] {
      _bn: <BN: 69b8857feab8184fb687f634618c035dac439dc1aeb3b5598a0f00000000001>
    },
    decimals: 9
  },
  quoteInfo: {
    mint: PublicKey [PublicKey(ERJ3xZbgULzw17swe5SSw1HmyGJJcb9hZodTq4fXHShh)] {
      _bn: <BN: c761262a8ee0c69b80b535e300dfa24babb207461f549ba7f66357b90182169c>
    },
    decimals: 7
  },
  lotSize: 10000,
  tickSize: 1e-10,
  dexProgramId: PublicKey [PublicKey(EoTcMgcDRTJVZDMZWBoU6rhYHZfkNTVEAfz3uUJRcYGj)] {
    _bn: <BN: cd0ebc1d9bfaddd6c92de05291d52f7b39929894d00def7441b6834db337be44>
  },
  computeBudgetConfig: { microLamports: 50000 }
}
`

**Comment by cruzshia** [comment]
fee units should be 600000(in example just type a random number), updated in commit - https://github.com/raydium-io/raydium-sdk-V2-demo/commit/692b67ad1a975f1f175869b054853a033140194a

**Comment by dexweb3** [comment]
> fee units should be 600000(in example just type a random number), updated in commit - [692b67a](https://github.com/raydium-io/raydium-sdk-V2-demo/commit/692b67ad1a975f1f175869b054853a033140194a)

At my case I didn't set units, just microLamports

**Comment by dexweb3** [comment]
> got it. I saw you have 2 comments. for createPool please set correct units and microLamports. for createMarket, currently haven't support add priority fee, if added it will exceed 1 ver tx limit.

Yes, I understand...

It's really strange that the interface allows setting an extra fee, but internally it doesn't check for overlimit. I quickly reviewed the internal code, and it looks like it prepares two transactions. It probably wouldn't be a problem to move some instructions to another transaction to allow for the addition of the extra fee (or even create a third transaction if necessary).
What do you think?

Is this situation now considered a bug, and is there a plan to fix it?

**Comment by cruzshia** [comment]
pull latest code and run yarn to update sdk, this should be resolved.

**Comment by dexweb3** [comment]
Thanks @cruzshia, it works now 👍
