### ISSUE TITLE
Program log: Error: ExpectedAccount',

### ISSUE THREAD

**Issue by mmdcuan** [raydium-io/raydium-sdk-V2-demo#82]
Program log: Error: ExpectedAccount', on routeSwap

**Comment by cruzshia** [comment]
Please provide full code block and wallet address so I can test it out, thanks

**Comment by mmdcuan** [comment]
const transaction = transactions[0]
            transaction.sign([owner]);
            txid = await connection.sendTransaction(transaction, {
                skipPreflight: false,
                maxRetries: 2,
            });

**Comment by mmdcuan** [comment]
how to filter fetchRoutePoolBasicInfo(), only new token?

**Comment by mmdcuan** [comment]
runs if using swapbaseout,
'Program log: Instruction: InitializeAccount',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3442 of 599550 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
    'Program routeUGWgWzqBWFcrCfv8tritsqukccJPu3q5GPP3xS invoke [1]',
    'Program log: process_swap_base_in_with_user_account:RouteSwapBaseInArgs { amount_in: 80044744, minimum_amount_out: 80102364 }',
    'Program log: Error: ExpectedAccount',
    'Program routeUGWgWzqBWFcrCfv8tritsqukccJPu3q5GPP3xS consumed 12244 of 596108 compute units',
    'Program routeUGWgWzqBWFcrCfv8tritsqukccJPu3q5GPP3xS failed: custom program error: 0x3'

**Comment by cruzshia** [comment]
fetchRoutePoolBasicInfo doesn't support any filter
I can't debug with only logs, I need full code block, thx

**Comment by mmdcuan** [comment]
expected account, successfully used swapbaseout

**Comment by mmdcuan** [comment]
I use routeSwap, only send transaction, 

 const { execute, transactions } = await raydium.tradeV2.swap({
    routeProgram: Router,
    txVersion,
    swapInfo: targetRoute,
    swapPoolKeys: poolKeys,
    ownerInfo: {
      associatedOnly: true,
      checkCreateATAOwner: true,
    },
    computeBudgetConfig: {
      units: 600000,
      microLamports: 10000,
    },
  })

  const transaction = transactions[0]
        transaction.sign([owner]);
        txid = await connection.sendTransaction(transaction, {
            skipPreflight: false,
            maxRetries: 2,
        });

**Comment by cruzshia** [comment]
please try run demo code, I tested it and works well
and try not to sign and manipulate transactions by yourself
<img width="953" alt="image" src="https://github.com/user-attachments/assets/522637be-f6c7-42c1-9dd7-eb4257489d55">

**Comment by mmdcuan** [comment]
actually just want skipPreflight: false, in the original menu it doesn't exist

**Comment by cruzshia** [comment]
yes, just use `const { txIds } = await execute({ sequentially: true, skipPreflight: false })`
cuz routeSwap might have more than 1 txs and your code might have bugs sometimes

**Comment by mmdcuan** [comment]
if using jito or fee from api?

const { data } = await axios.get<{
    id: string
    success: boolean
    data: { default: { vh: number; h: number; m: number } }
  }>(`${API_URLS.BASE_HOST}${API_URLS.PRIORITY_FEE}`)
how ?

**Comment by mmdcuan** [comment]
skipPreflight: true will drain the fee if an error occurs and the bot continues to execute

**Comment by mmdcuan** [comment]
on log 
1728421175428 Raydium_tradeV2 sdk logger debug ["direct error",6,"HAwjqG1Vg1XHvYqudzX9xAtb8akyttYStDC7NBWj9NWW","No enough initialized tickArray"]

**Comment by cruzshia** [comment]
That means your clmm pool don't have enough liquidity so it will not able to be swappable route.

**Comment by mmdcuan** [comment]
thanks
