### ISSUE TITLE
How to completely destroy a Raydium instance?

### ISSUE THREAD

**Issue by liu798675179** [raydium-io/raydium-sdk-V2-demo#84]
Define the raydium instance in a function, which is used for swap transactions. Use load() to initialize the instance and pass in the owner field. The instance is not destroyed after the function is run. Account information is always requested regularly. When the function is called multiple times, the network will be congested and the memory will continue to accumulate. 

After using the `raydium.account.updateTokenAccount(await fetchTokenAccountData())` method, the network congestion is resolved, but the memory is still slowly increasing, and it feels like there are still instances that have not been destroyed.

@cruzshia @rudy5348  help me check it please, thanks. 

```js
const raydium = await Raydium.load({
        connection,
        owner: ownerKeypair,
        cluster,
        disableFeatureCheck: true,
        disableLoadToken: true,
        blockhashCommitment: "finalized",
      });

// other codes
// ......

try {
          raydium.account.updateTokenAccount(
            await this.fetchTokenAccountData(ownerKeypair.publicKey)
          );

          connection.onAccountChange(ownerKeypair.publicKey, async () => {
            if (raydium && raydium.account) {
              raydium.account.updateTokenAccount(
                await this.fetchTokenAccountData(ownerKeypair.publicKey)
              );
            }
          });
        } catch (e) {
          console.log("raydium error", e);
        } finally {
          if (raydium) {
            raydium.owner = null;
            raydium = null;
          }

          if (connection) {
            connection = null;
          }
}
```

**Comment by cruzshia** [comment]
Sdk doesn't run any jobs in background and due to javascript's garbage collection mechanism, we don't provide destroy function that js will release memory automatically.

**Comment by liu798675179** [comment]
> Sdk doesn't run any jobs in background and due to javascript's garbage collection mechanism, we don't provide destroy function that js will release memory automatically if variables/objects are not used anywhere.

Yeah, that's the weirdest part. Let me monitor this carefully for a while longer.

**Comment by liu798675179** [comment]
When I comment out the business code in the function and only keep the initialization code of Raydium, and call the function regularly, the memory also increases slowly. When I comment out the relevant code of Raydium and call the function regularly, the memory tends to be stable. So it is likely that Raydium has similar scheduled tasks, event monitoring, closures, etc. after initialization? So it has been occupying resources and cannot be destroyed?

**Comment by cruzshia** [comment]
this only thing SDK might have is only watching token account changes here https://github.com/raydium-io/raydium-sdk-V2/blob/master/src/raydium/account/account.ts#L124, nothing else.
if you don't need sdk watch token account change event, you can manage token account by yourself, example: updateTokenAccount
and raydium UI also uses SDK v2 and don't have such problem

**Comment by cruzshia** [comment]
SDK code is open source you can review it (initialize code here: https://github.com/raydium-io/raydium-sdk-V2/blob/master/src/raydium/raydium.ts#L154), there's no jobs run inside , and if you also can check your code whether access data from sdk might cause closures, thx

**Comment by liu798675179** [comment]
This problem is solved. The problem is that the connection will automatically subscribe to account change information. After each call, the listener needs to be removed.
`
let connection = new Connection(
        "rpc",
        "confirmed"
      );

let raydium = await Raydium.load({
        connection,
        owner: ownerKeypair,
        cluster,
        disableFeatureCheck: true,
        disableLoadToken: true,
        blockhashCommitment: "finalized",
      });

const swapResult = CurveCalculator.swap(
          inputAmount,
          buyType ? poolInfo.baseReserve : poolInfo.quoteReserve,
          buyType ? poolInfo.quoteReserve : poolInfo.baseReserve,
          poolInfo.poolInfo.configInfo.tradeFeeRate
        );

const { transaction } = await raydium.cpmm.swap({
          poolInfo: poolInfoApiV3PoolInfoItem,
          poolKeys: undefined,
          inputAmount,
          swapResult,
          slippage, // range: 1 ~ 0.0001, means 100% ~ 0.01%
          baseIn,
        });

// other codes
.....


// when finished
raydium.account.notSubscribeAccountChange = true;

        if (!raydium.account.notSubscribeAccountChange) {
          raydium.account.updateTokenAccount(
            await this.fetchTokenAccountData(ownerKeypair.publicKey)
          );
        }

// important
connection.removeAccountChangeListener(0);
`

'connection.removeAccountChangeListener(0);' very important after call.

**Comment by rileyg98** [comment]
It appears that raydium may not be correctly cleaning the subscribers up on destruction, which causes the Solana websocket listener to keep them in memory waiting to be run, causing a memory leak.

**Comment by cruzshia** [comment]
version 0.1.93-alpha sdk update not auto subscribe account change initially.
also add raydium.account.clearAccountChangeCkb() method to clear cbk only if you set to subscribe in load function
```
Raydium.load({
 ...
 notSubscribeAccountChange:false 
})
```

**Comment by rileyg98** [comment]
Yes, it seems a related update to the code caused that. I've resolved the problem. Thank you.
