### ISSUE TITLE
createMarket error!!!!

### ISSUE THREAD

**Issue by wangke329** [raydium-io/raydium-sdk-V2-demo#89]
I am using this demo to create a pool. When I execute the creation market, it prompts me "undefined", but I find that it deducts 1.8 SOL from me. I want to know what I can do to continue to create, instead of repeatedly deducting my 1.8 SOL?

**Comment by wangke329** [comment]
What I created here is the amm pool.

**Comment by wangke329** [comment]
create market total 2 txs, market info:  {
  marketId: 'BNmYSqfcJeehdRAKrhwEiVUbm4h9aMRvMfBgF7vzwdRD',
  requestQueue: '5SAwe9a2NdASF7z3SBouUKcpZEJET6FQPNXtWD6W7XBh',
  eventQueue: 'CbUP7YLHQ3jm6yMEf7aPSHoY6LftJv9SLdA7gRgkPCKZ',
  bids: 'HZRTgSyy6nNoqZJZXDuBjG2GYX9kbVs5FEQWMKR4HH25',
  asks: 'EhhVJystGcizVQ6TxfjpCWxL4gs9KUEAaeG9KRJjpJob',
  baseVault: 'HQJDB2sYPfXSitBkThwLLzxignEBiXNG4Fwgw4CAstr4',
  quoteVault: '2mKy9HeATvzvNpjjNqhV8TUuNUokxhpW7MNTE1csru5e',
  baseMint: 'okDFNbhRWYi1NpQyFrR4Uzx2vR1RAMnW3N4VHs3Mint',
  quoteMin: 'So11111111111111111111111111111111111111112'
}
simulate tx string: [
  'AQIZe/XH6/hViVPEBYxIytS/Led8xez47Fy9gNVB+aUwutvgeX4+1A3BTd1rv5aj2s6iRT+KN6f4tHvEf1LcvA6AAQAFC5CkoZV3SD/t6kLxyNR61v55ZTNyYrOs7Pn7l4RoVqup87LPBx4UIba4zTp5LRctEX0SUrLd8aBPj468uvdqFUkaNrCPgevZqp3I/jLuNiNSmokSwmpVGPk9ScSZwIEkhZoobiQpaXAGBmCycwNKIX2BaDGkX932bl0rXqz3KxEsQeGCbPFE+GZjYC4fw7fptu9j8G//0mVqdwF7i+hG3wSsRUOHMTJPtEu0pYxMgeXTqYVLXEpOV9rna7+n9BdIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABt324ddloZPZy+FGzut5rBy0he1fWzeROoz1hX7/AKkL+ZOEl9eWR++mBHzU/Q1KrbUZB++aS+4Nsdaq8sPSqc5UFRGa9yuSVSxagetH/hlU+o0+qBJKSW77X/RjiuTHBpuIV/6rgYT7aH9jRhjANdrEOdwa6ztVmKDwAAAAAAEdIUq1RX+Q312lXHqx8XWI/Afq/AOZXVjRdT/gyusd9QcGAgABfAMAAACQpKGVd0g/7epC8cjUetb+eWUzcmKzrOz5+5eEaFarqSAAAAAAAAAAM3JLRldWOWVlYldYOVpYbTlUVThVZnJibzY3YTZWR0fwHR8AAAAAAKUAAAAAAAAABt324ddloZPZy+FGzut5rBy0he1fWzeROoz1hX7/AKkGAgACfAMAAACQpKGVd0g/7epC8cjUetb+eWUzcmKzrOz5+5eEaFarqSAAAAAAAAAAMlRMeUMzUFRSS2R6c3dReEQ2TFlpVnpxUGhzdlJIcW7wHR8AAAAAAKUAAAAAAAAABt324ddloZPZy+FGzut5rBy0he1fWzeROoz1hX7/AKkHBAEICQsBAQcEAgoJCwEBBgIAA3wDAAAAkKShlXdIP+3qQvHI1HrW/nllM3Jis6zs+fuXhGhWq6kgAAAAAAAAADlnUmNuYTY0MW50Mjk4dmlKN2pRVlRxNjNEdGtyTWdUwMw2AAAAAACEAQAAAAAAAA0HUagoLaYTBf4pnDe5mOWEcdsRNQNzEPi+EEWmCvbuBgIABHwDAAAAkKShlXdIP+3qQvHI1HrW/nllM3Jis6zs+fuXhGhWq6kgAAAAAAAAADJVUkttdFJYeWQ0YnFZc3N4NEE0VXpqVDhyVThrMjVtQJ4uAgAAAAAMFAAAAAAAAA0HUagoLaYTBf4pnDe5mOWEcdsRNQNzEPi+EEWmCvbuBgIABXwDAAAAkKShlXdIP+3qQvHI1HrW/nllM3Jis6zs+fuXhGhWq6kgAAAAAAAAAHVrNzFwZWtLTmFNaDVydzNTRnBWVkFKeGNWZ1JDd3hmQN7ObAAAAAAMAAQAAAAAAA0HUagoLaYTBf4pnDe5mOWEcdsRNQNzEPi+EEWmCvbuARmPH0w6RSJj1BOyzRfry8Gg5YhzZOYmGhKoF5LqFlo+AAEF',
  'AbaJzlR83HCCUGgV7/XrO9rS/64loyVo53vELyGiZnIC8GRrgGOeMNs53XsuXfAdXIisfdBbiYgxJFzuafFpbgWAAQAEDJCkoZV3SD/t6kLxyNR61v55ZTNyYrOs7Pn7l4RoVqup9gk71WT187FxWLuqCrpf8bfcw8smKuRxvfw/t5PavK7LlPFEbIkWbNJoKdDxobmHIvaq8WebIF3SbRKs2BjYipoobiQpaXAGBmCycwNKIX2BaDGkX932bl0rXqz3KxEsQeGCbPFE+GZjYC4fw7fptu9j8G//0mVqdwF7i+hG3wSsRUOHMTJPtEu0pYxMgeXTqYVLXEpOV9rna7+n9BdIwPOyzwceFCG2uM06eS0XLRF9ElKy3fGgT4+OvLr3ahVJGjawj4Hr2aqdyP4y7jYjUpqJEsJqVRj5PUnEmcCBJIUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0HUagoLaYTBf4pnDe5mOWEcdsRNQNzEPi+EEWmCvbuC/mThJfXlkfvpgR81P0NSq21GQfvmkvuDbHWqvLD0qkGm4hX/quBhPtof2NGGMA12sQ53BrrO1WYoPAAAAAAAR0hSrVFf5DfXaVcerHxdYj8B+r8A5ldWNF1P+DK6x31AwgCAAF8AwAAAJCkoZV3SD/t6kLxyNR61v55ZTNyYrOs7Pn7l4RoVqupIAAAAAAAAABGTm5iUEF0TVNHYjNvdVd1NThqTkFydGtvZG1VQU1IUEDePhsAAAAADAABAAAAAAANB1GoKC2mEwX+KZw3uZjlhHHbETUDcxD4vhBFpgr27ggCAAJ8AwAAAJCkoZV3SD/t6kLxyNR61v55ZTNyYrOs7Pn7l4RoVqupIAAAAAAAAAA3ak1nUjhqNVRVdmJ1REwzRVhlU25pUUpCTm9MY3pDV0DePhsAAAAADAABAAAAAAANB1GoKC2mEwX+KZw3uZjlhHHbETUDcxD4vhBFpgr27gkKAwQFAQIGBwoLDCcAAAAAAEBCDwAAAAAAZAAAAAAAAAAAAAMAAAAAAAAAZAAAAAAAAAABGY8fTDpFImPUE7LNF+vLwaDliHNk5iYaEqgXkuoWWj4AAQU='
]
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}


please help me!!!!

**Comment by cruzshia** [comment]
according the simulate tx string, this market `BNmYSqfcJeehdRAKrhwEiVUbm4h9aMRvMfBgF7vzwdRD` has been created successfully in this tx https://explorer.solana.com/tx/3SD9yaNqdcWJssTGAc7uER1VUXA1wwTejcy1GYG69t9itdHUaifAHwyfHCQoMqQR5TipMX3CNDuy6LKoZ79YWq3
and second tx for initializing market didn't go through successfully which might cause by you didn't set enough priority fee for tx (network is congestion recently), you can try sending second tx only to initialize market only but not resent both 2 txs again.
when the initialize market tx go through, create market is done.
second tx simulation result here: https://explorer.solana.com/tx/inspector?signatures=%255B%25224eg1CGRgKRRYG699kMUP7fAFx9DkMPfsoGLea9EN1wVHLp2wic6heg7y5DBgzQcNWHPqhs9ukmuP4U6W1ZVpbLxc%2522%255D&message=gAEABAyQpKGVd0g%252F7epC8cjUetb%252BeWUzcmKzrOz5%252B5eEaFarqfYJO9Vk9fOxcVi7qgq6X%252FG33MPLJirkcb38P7eT2ryuy5TxRGyJFmzSaCnQ8aG5hyL2qvFnmyBd0m0SrNgY2IqaKG4kKWlwBgZgsnMDSiF9gWgxpF%252Fd9m5dK16s9ysRLEHhgmzxRPhmY2AuH8O36bbvY%252FBv%252F9JlancBe4voRt8ErEVDhzEyT7RLtKWMTIHl06mFS1xKTlfa52u%252Fp%252FQXSMDzss8HHhQhtrjNOnktFy0RfRJSst3xoE%252BPjry692oVSRo2sI%252BB69mqncj%252BMu42I1KaiRLCalUY%252BT1JxJnAgSSFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANB1GoKC2mEwX%252BKZw3uZjlhHHbETUDcxD4vhBFpgr27gv5k4SX15ZH76YEfNT9DUqttRkH75pL7g2x1qryw9KpBpuIV%252F6rgYT7aH9jRhjANdrEOdwa6ztVmKDwAAAAAAEdIUq1RX%252BQ312lXHqx8XWI%252FAfq%252FAOZXVjRdT%252Fgyusd9QMIAgABfAMAAACQpKGVd0g%252F7epC8cjUetb%252BeWUzcmKzrOz5%252B5eEaFarqSAAAAAAAAAARk5uYlBBdE1TR2Izb3VXdTU4ak5BcnRrb2RtVUFNSFBA3j4bAAAAAAwAAQAAAAAADQdRqCgtphMF%252FimcN7mY5YRx2xE1A3MQ%252BL4QRaYK9u4IAgACfAMAAACQpKGVd0g%252F7epC8cjUetb%252BeWUzcmKzrOz5%252B5eEaFarqSAAAAAAAAAAN2pNZ1I4ajVUVXZidURMM0VYZVNuaVFKQk5vTGN6Q1dA3j4bAAAAAAwAAQAAAAAADQdRqCgtphMF%252FimcN7mY5YRx2xE1A3MQ%252BL4QRaYK9u4JCgMEBQECBgcKCwwnAAAAAABAQg8AAAAAAGQAAAAAAAAAAAADAAAAAAAAAGQAAAAAAAAAARmPH0w6RSJj1BOyzRfry8Gg5YhzZOYmGhKoF5LqFlo%252BAAEF

**Comment by wangke329** [comment]
Yes, I understand. I just want to skip the first step of creating a market and go straight to the second step of initializing the market. But I don't see the split API in the code of the SDK. These two steps are combined into a single API, market2.craete.

**Comment by cruzshia** [comment]
raydium.marketV2.create returns all data you needed so you can send or modify tx by yourself like below
```
  const {transactions, signers } = await raydium.marketV2.create({ xxx })
  const tx = transactions[1] as VersionedTransaction
  tx.sign(signers[1])
  const txId = await raydium.connection.sendTransaction(tx, { skipPreflight: false })
  await confirmTransaction(raydium.connection, txId)
```

**Comment by wangke329** [comment]
Okay, thank you very much for providing the information. They are very helpful to me.

**Comment by retrofinger** [comment]
We are experiencing the exact same problem as @wangke329 (on devnet) but we found out that the createMarket.ts script works fine if we use a token previously minted via Solana CLI (meaning it's an SPL Standard Token). However, when we use our own custom token which utilizes the transfer_hook functionality (based on the official Solana program examples), the market initialization fails (just as for @wangke329 and without any useful error reporting). We then tried to cut out the extensions (MetadataPointer and TransferHook) from our custom token but the problem remained the same. 

FYI: Our custom token works properly, the transfer_hook extension works well, no problems at all during transferring or testing. Also, for the creation of a Market, the transfer_hook function is not even invoked. We even tested this by always returning Ok(()) in transfer_hook() just in case, to be sure.

The problem remains and we are unable to programmatically create a market using the createMarket.ts script for our token. 

Can someone kindly have a look at what might be going on? Here is a test token mint address on devnet: 
 6hBYUFddtXwEaJD9VLajydbnm6riyn8niRfELfR3YD4W
 
 Thanks!

**Comment by retrofinger** [comment]
After running the transactions separately and manually, the error we got was this:

    'Program log: Instruction: InitializeAccount',
    'Program log: Error: IncorrectProgramId',
    
Interestingly, since this problem does not occur with a standard SPL token but does occur with our custom token, we assume that the program id is not correctly set internally within **raydium.marketV2.create()**. This would explain the error. 

Also, interestingly, when running **raydium.token.getTokenInfo()** on our custom token, we get this:

`  chainId: 101,
  address: '6hBYUFddtXwEaJD9VLajydbnm6riyn8niRfELfR3YD4W',
  programId: 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb',
  logoURI: '',
  symbol: '6hBYUF',
  name: '6hBYUF',
  decimals: 6,
  tags: [],
  extensions: {},
  priority: 0,
  type: 'unknown'
}`

How and why does your function return the wrong program id here? Because **TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb** is the program id of the SPL standard 2022 token program, but shouldn't it be our custom program id?

We are not sure if the same logic as in **raydium.token.getTokenInfo()** is applied internally when fetching information on the token, but if so, then it would explain the error?

**Comment by retrofinger** [comment]
We just found out that createMarket.ts fails on any token that runs on the SPL TOKEN 2022 standard. It only works for the regular default SPL token. Either we are missing a setting or parameter, or there is a bug in your code?

**Comment by cruzshia** [comment]
CreateMarket doesn't support 2022
