### ISSUE TITLE
poolInfo get null

### ISSUE THREAD

**Issue by freak9527** [raydium-io/raydium-sdk-V2-demo#9]
when listening add Liquidity Pool AMM,
then use raydium-sdk-V2-demo/src/amm/swap.ts to swap, 
but   

> const poolInfo = data[0] as ApiV3PoolInfoStandardItem

 return null。
A few minutes later it's ok。 tk

**Comment by cruzshia** [comment]
api has some delay to return new created pool info, you should wait for some minutes.

**Comment by freak9527** [comment]
have any way to quick swap with rayduim-sdk

**Comment by freak9527** [comment]
have any way to quick swap with rayduim-sdk
