### ISSUE TITLE
Perform swap/quote across multiple pools with Liquidity

### ISSUE THREAD

**Issue by PiciuU** [raydium-io/raydium-sdk-V2-demo#90]
Hi,

Is it possible to perform a swap/calculate a quote using the Liquidity module when passing through multiple pools?

For example, I can calculate a quote for a single pool using the following method: 

```ts
const quoteOutput = raydium.liquidity.computeAmountOut({
    poolInfo: {
        ...pool.details.poolInfo,
        baseReserve,
        quoteReserve,
        status,
        version: 4,
    },
    amountIn: new BN(amountIn),
    mintIn: mintIn.publicKey,
    mintOut: mintOut.publicKey,
    slippage: SWAP_SLIPPAGE,
});
```

However, I want to calculate the quote based on a route involving multiple pools.

In my case, I have two devnet AMM pools:

SOL/WETH: `0xCBCdF9626bC03E24f779434178A73a0B4bad62eD`
SOL/USDC: `0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640`
I am trying to perform a swap from WETH to USDC by routing through these two pools.

Is this possible using the liquidity module, or do I need to use tradeV2 for this functionality?

Thank you!

**Comment by cruzshia** [comment]
1. If you want to use route swap, only trade/swap or api/swap support it, amm/swap is only for "single pool" swap, I would suggest you use api/swap for easier development.
2. Code here is just for demo usage, if code runs after await execute(xx) and means tx is completed, raydium UI uses the same logic, so there's no problem here.

**Comment by PiciuU** [comment]
Hmm okay, so I use trade/swap for now, but I see another problem that occurs and it is quite problematic.

Thats my code for swap functionality:
```ts
try {
    const { execute } = await this.raydium.tradeV2.swap({
        routeProgram: new solana.PublicKey(Config.constants.routerAddress),
        txVersion: TxVersion.V0,
        swapInfo: quote.targetRoute,
        swapPoolKeys: quote.poolKeys,
        ownerInfo: {
            associatedOnly: true,
            checkCreateATAOwner: true,
        },
    })

    Logger.info("Executing transaction:")
    const { txIds } = await execute({ sequentially: true })
    Logger.info('txIds:', txIds)
    txIds.forEach((txId) => Logger.info(`https://explorer.solana.com/tx/${txId}`))

    return true;
} catch(error) {
    Logger.error("Error while sending swap transaction:", error);
    return false;
}
```
When I use the publicly available rpc solana, `https://api.mainnet-beta.solana.com`, the code executes correctly and executes this part of the code

```ts
Logger.info("Executing transaction:")
const { txIds } = await execute({ sequentially: true })
Logger.info('txIds:', txIds)
txIds.forEach((txId) => Logger.info(`https://explorer.solana.com/tx/${txId}`))
```

But when I use another rpc, for example from chainstack or alchemy, the above lines no longer execute. It looks as if the program is still waiting for tradeV2.swap to resolve, until the timeout is finally exceeded and caught by the catch. This means that the transaction cannot be executed even though the only difference is the RPC endpoint. Of course, the endpoint works correctly, for example it returns all information about the wallet or quotes

**Comment by cruzshia** [comment]
you can simulate your tx  like this way:
https://github.com/raydium-io/raydium-sdk-V2-demo/issues/92#issuecomment-2442086716
sequentially must be true or if there're more than 1 tx, txs will not execute in correct order and txs might be fail.
sequentially:true means second tx will execute after first one got confirmed, if if shows timeout means you need to set higher priority fees in your tx
```
computeBudgetConfig: {
      units: 600000,
      microLamports: 1000000,
    },
```

if your code can run to execute part means good, the only thing you should do is to simulate it check what's going on and adjust the priority fees
