### ISSUE TITLE
how to perform swap from raydium token to SOL?

### ISSUE THREAD

**Issue by ParzifaL-03** [raydium-io/raydium-sdk-V2-demo#93]
anyone can tell me the flow to swap from from raydium token to SOL, since i already success swap from SOL to raydium token using Raydium.Liquidity.swap method

also Is there a discord channel or something like that to discuss for more detail?

**Comment by ParzifaL-03** [comment]
i also want to ask about this method `Raydium.account.getOrCreateTokenAccount, try to make some custom instructions instead i use `Raydium.liquidity.swap` method, and i always got the swap is not success but the simulate transaction is running fine like this screenshots
![image](https://github.com/user-attachments/assets/de6764da-8e3a-44c2-8f73-07a5556a4787)

**Comment by cruzshia** [comment]
Since sdk has no issue, so I will close this one.
For more development discussion, please go to discord channel https://discord.com/invite/raydium
