### ISSUE TITLE
poolData Increment get

### ISSUE THREAD

**Issue by lh232510** [raydium-io/raydium-sdk-V2-demo#95]
poolData = await raydium.tradeV2.fetchRoutePoolBasicInfo()

It is very troublesome to obtain the full amount every time because the pool is created in real time. Is there any way to increase the acquisition pool?

**Comment by cruzshia** [comment]
we only have this method at this moment, looking into code here https://github.com/raydium-io/raydium-sdk-V2/blob/master/src/raydium/tradeV2/trade.ts#L323C54-L323C72 you can find out what it does is to call connection.getProgramAccounts by amm/clmm/cpmm program, maybe you can try reduce length of `dataSlice`  or just getProgramAccounts for specific program
