### ISSUE TITLE
Error when running src/trade/routeSwap.ts

### ISSUE THREAD

**Issue by GuiFlam** [raydium-io/raydium-sdk-V2-demo#99]
Hi everyone. I am trying to programatically swap SOL for another token on Devnet. I have already succeeded but the transaction seems to never go through (other than the 2 times I've succeeded). I don't really understand why it would work only a couple of times and not always. 

Can anyone help?

Here is the transaction when it faisl https://solana.fm/tx/ecmZNCBPHXqD8r46zGknYYgXsjofYFcZHdyLC4dHWN4KWREehDx15ZGTCisZP8cTRJXoDhziEJzFYEkKzsQL3kM?cluster=devnet-alpha

Here is the transaction when it succeeds: https://solana.fm/tx/2HaadMEgmX6XNRpcrN136U75x9283xF4DoJqyNRhMhAQNo9hsHzD9EYinSTZitG1aCoTR6njGxVbJ5fcz7NKcSkA?cluster=devnet-alpha

Here is the console output:
```guifl@xps15:~/Desktop/raydium-sdk-V2-demo$ yarn dev src/trade/routeSwap.ts 

yarn run v1.22.22
$ ts-node src/trade/routeSwap.ts
connect to rpc https://devnet.helius-rpc.com/?api-key=5a33c297-cc93-4595-8d0d-ef65e7260103 in devnet
(node:101577) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
reading cache pool data
read cache pool data success
computing swap route..
fetching amm pools info, total:  64
fetching cpmm pools info, total:  0
fetching mints info, total:  0
fetching clmm pools info, total: 0
calculating available swap routes...
1731546586413 Raydium_tradeV2 sdk logger debug ["direct done"]
best swap route: {
  input: '0.1',
  output: '0.5270572',
  minimumOut: '0.521786628',
  swapType: 'route',
  routes: 'AMM A286FQ6Gbmarojw5VtkHYPHVW7p3gUxfmAJag1QQb27J 6 -> AMM 87J1SHPAtWFP6zTas65jDVRwnWZRprWNLo59h3vtKZwW 7'
}
fetching swap route pool keys..
build swap tx..
Server responded with 429 Too Many Requests.  Retrying after 500ms delay...
Server responded with 429 Too Many Requests.  Retrying after 1000ms delay...
you can paste simulate tx string here: https://explorer.solana.com/tx/inspector and click simulate to check transaction status
if tx simulate successful but did not went through successfully after running execute(xxx), usually means your txs were expired, try set up higher priority fees
strongly suggest use paid rpcs would get you better performance
execute tx..
simulate tx string: [
  'ASBwb/4BMnZL6JOeI7wx1jb/Jr8My8Y7bdN8M/kUNXJXdzj09k/hQ8oHawUaAsFn2K9K5rO6lPPhSv8xom0adQKAAQAJFturjc66f0wNZu7nAh82nvbMMYUjSU+mG4so/uGNusIPdb/7IwXSakSpAeNJFiS4czpfPvYWkXKGhbpbTy5QoRsGm4hX/quBhPtof2NGGMA12sQ53BrrO1WYoPAAAAAAAVAoRMJ5hWAcxfnKcM5M9ZFCt3kzt1TQ5MfZPDeSaU1pMJMI2qQwVKJtcKG3rk7DpxxJSeAcTVHndSG1A5DmIMz0XrKdIK+cRD/dPx13xod+gpBlDullGOH8iLwMnF8Ji4YCx8dWhkPVrWFly1UciQxGhpIdE6mVREGVyg+Igx4xjp1sispRm6zO61sjF1peQ1yLdVO0DSNvfComp7gWcARW4XN5+BOw7gGBEeoAYuRoSxCUqHqurfPkbESai2VpJgc1N/CvpQ+o8btytr6vt6sqNANd+AldynPYmKMgv7ZWaZ6GF6Hx76MQ3IerTSC4raT5p3RPsuI5odytWDx0XHli3pldxvozHqTyqvKnKY9GuFQVNQdl+NDb81Ul6Tpam3zKuFC942utYUISC0DUzUhQ+3yJblqCdR2Ik62avD0eAwZGb+UhFzL/7K26csOb57yM5bvF9xJrLEObOkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbd9uHXZaGT2cvhRs7reawctIXtX1s3kTqM9YV+/wCpBqfVFxksXFEhjMlMPUrxf1ja7gibof1E49vZigAAAACbzlw3l8dSGIegU4Aza6AVed6vK/606NGbcunh8ncV+wbd9uHudY/eGEJdvORszdq2GvxNg7kNJ/69+SjYoYv8jJclj04kifG7PRApFI4NgwtaE5na/xCEBI572Nvp+Fn1aCsG/MvbprQNI0oUsffenYteEeRacryqkmI/Pmd6G7sc8KMrGdy+1jlvLpZxbQX1Ed7AHQ9l/XWG3WREqk2PRrM49hdQv+teQgv/EY04IZyxUrAbtgrSGTKxKRFmW6kGDQAJA0BCDwAAAAAADQAFAqCGAQAOAgABfAMAAADbq43Oun9MDWbu5wIfNp72zDGFI0lPphuLKP7hjbrCDyAAAAAAAAAARUNQOWRXRmhhODlmTTJTWHA3NmpBTTd2b1hkRm9hUEzw/hQGAAAAAKUAAAAAAAAABt324ddloZPZy+FGzut5rBy0he1fWzeROoz1hX7/AKkPBAECABABAREpDxITDgABAxQEAgUGFQYGBgcIBgYGBgYGFAMFCQoVCgoKCwwKCgoKCgoRAADh9QUAAAAABNUZHwAAAAAPAwEAAAEJAA=='
]
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Object]".
    at throwUnhandledRejectionsMode (node:internal/process/promises:392:7)
    at processPromiseRejections (node:internal/process/promises:475:17)
    at processTicksAndRejections (node:internal/process/task_queues:106:32) {
  code: 'ERR_UNHANDLED_REJECTION'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by cruzshia** [comment]
you can simulate your tx [here](https://explorer.solana.com/tx/inspector?cluster=devnet&signatures=%255B%2522ecmZNCBPHXqD8r46zGknYYgXsjofYFcZHdyLC4dHWN4KWREehDx15ZGTCisZP8cTRJXoDhziEJzFYEkKzsQL3kM%2522%255D&message=gAEACRbbq43Oun9MDWbu5wIfNp72zDGFI0lPphuLKP7hjbrCD3W%252F%252ByMF0mpEqQHjSRYkuHM6Xz72FpFyhoW6W08uUKEbBpuIV%252F6rgYT7aH9jRhjANdrEOdwa6ztVmKDwAAAAAAFQKETCeYVgHMX5ynDOTPWRQrd5M7dU0OTH2Tw3kmlNaTCTCNqkMFSibXCht65Ow6ccSUngHE1R53UhtQOQ5iDM9F6ynSCvnEQ%252F3T8dd8aHfoKQZQ7pZRjh%252FIi8DJxfCYuGAsfHVoZD1a1hZctVHIkMRoaSHROplURBlcoPiIMeMY6dbIrKUZuszutbIxdaXkNci3VTtA0jb3wqJqe4FnAEVuFzefgTsO4BgRHqAGLkaEsQlKh6rq3z5GxEmotlaSYHNTfwr6UPqPG7cra%252Br7erKjQDXfgJXcpz2JijIL%252B2Vmmehheh8e%252BjENyHq00guK2k%252Bad0T7LiOaHcrVg8dFx5Yt6ZXcb6Mx6k8qrypymPRrhUFTUHZfjQ2%252FNVJek6Wpt8yrhQveNrrWFCEgtA1M1IUPt8iW5agnUdiJOtmrw9HgMGRm%252FlIRcy%252F%252BytunLDm%252Be8jOW7xfcSayxDmzpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG3fbh12Whk9nL4UbO63msHLSF7V9bN5E6jPWFfv8AqQan1RcZLFxRIYzJTD1K8X9Y2u4Im6H9ROPb2YoAAAAAm85cN5fHUhiHoFOAM2ugFXneryv%252BtOjRm3Lp4fJ3FfsG3fbh7nWP3hhCXbzkbM3athr8TYO5DSf%252Bvfko2KGL%252FIyXJY9OJInxuz0QKRSODYMLWhOZ2v8QhASOe9jb6fhZ9WgrBvzL26a0DSNKFLH33p2LXhHkWnK8qpJiPz5nehu7HPCjKxncvtY5by6WcW0F9RHewB0PZf11ht1kRKpNj0azOPYXUL%252FrXkIL%252FxGNOCGcsVKwG7YK0hkysSkRZlupBg0ACQNAQg8AAAAAAA0ABQKghgEADgIAAXwDAAAA26uNzrp%252FTA1m7ucCHzae9swxhSNJT6Ybiyj%252B4Y26wg8gAAAAAAAAAEVDUDlkV0ZoYTg5Zk0yU1hwNzZqQU03dm9YZEZvYVBM8P4UBgAAAAClAAAAAAAAAAbd9uHXZaGT2cvhRs7reawctIXtX1s3kTqM9YV%252B%252FwCpDwQBAgAQAQERKQ8SEw4AAQMUBAIFBhUGBgYHCAYGBgYGBhQDBQkKFQoKCgsMCgoKCgoKEQAA4fUFAAAAAATVGR8AAAAADwMBAAABCQA%253D)

just simulated your tx and looks like wrong computeBudgetConfig settings, pushed a commit https://github.com/raydium-io/raydium-sdk-V2-demo/commit/514d513dd346144cdda22e5fc5323db3429be468#diff-1cccd777077d6bd8943af4b047c4edd63f9c08d450ea1c051d4f73d55b6ca429R146 , you can try again directly or set up different microLamports

<img width="1148" alt="image" src="https://github.com/user-attachments/assets/a0a7c800-815a-418a-b828-3225d850df42">
